site_name: Python Book
site_url: https://ag999git.github.io/001-mkdocs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy

# This replaces your GitBook summary.md! 
# You will add your chapter files here later.
nav:
  - Home: index.md

docs_dir: docs

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - toc:
      permalink: true

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
