site_name: Python 999
site_url: https://ag999git.github.io/001-mkdocs/
# These two lines fix your broken repository icon link:
repo_url: https://github.com/ag999git/001-mkdocs
repo_name: ag999git/001-mkdocs

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - content.code.copy
    - toc.integrate

docs_dir: docs

plugins:
  - search
  - awesome-pages
  - mknotebooks

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
