<a href="https://colab.research.google.com/github/ag999git/001-Python-book-2026/blob/main/colab-nb/13-10-regular-exp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 13: Regular Expressions (RE)

This notebook holds the code examples of Chapter 13. You do not need to type them. Run them, read the notes, and then change the code to see what happens.

A **regular expression** is a small language for describing patterns in text. With it you can ask: does this text follow the rule? Where does the pattern occur? Can I pull out the parts I need, or replace them?

The chapter has three parts, and so has this notebook:

| Part | What it covers |
|---|---|
| **A** | The ideas of regular expressions: what to match, where, how many times, and how parts are combined |
| **B** | The `re` module of Python: the Pattern object, the Match object, and the functions and methods that use them |
| **C** | Advanced topics: capturing and non-capturing groups, backreferences and lookarounds |

### How this notebook is arranged

- Each code example from the book is in its own code cell.
- Before every example there is a text cell. It tells you what the code does, how it does it, why it matters, and what you should learn from it.
- Some examples also have a text cell after them. Its heading starts with "Notes on Example" and the example number, so you always know which code cell it talks about.
- A few short cells are marked **Try it**. They are not in the book. They let you see something the book describes in words.
- At the end of every section there is a link that takes you back to the Table of Contents.
- A short "Beyond the Book" section at the end adds a few extras. You can skip it on the first reading.

### How to run the code

1. Click inside a code cell.
2. Press **Shift + Enter**, or click the round Run button on the left of the cell.
3. The result appears just below the cell.

Run the cells from top to bottom. The `re` module is part of the Python standard library, so there is nothing to install. Just write `import re`.

**Always write your patterns as raw strings**, that is with an `r` in front: `r"\d+"`. Without the `r`, Python treats the backslash as an escape character and your pattern may break.

### How to read the flowcharts

The steps are numbered 1, 2, 3 and so on. When the flow splits into two paths, one path uses the letter A (2A, 3A ...) and the other uses the letter B (2B, 3B ...). A long chain of steps is folded onto a second row: follow the arrow down and back to the left.

## <a name="toc"></a>Table of Contents

- [Learning objectives](#learning-objectives)
- [Part A: A general discussion of regular expressions](#part-a-a-general-discussion-of-regular-expressions)
- [13.1 Introduction](#13-1-introduction)
- [13.2 The concept of a regular expression](#13-2-the-concept-of-a-regular-expression)
- [13.3 What a regular expression is](#13-3-what-a-regular-expression-is)
- [13.4 Character specifiers: what to match](#13-4-character-specifiers-what-to-match)
    - [13.4.1 Characters that match themselves](#13-4-1-characters-that-match-themselves)
    - [13.4.2 Special characters that match something other than themselves](#13-4-2-special-characters-that-match-something-other-than-th)
- [13.5 Which single character from a set: the character class](#13-5-which-single-character-from-a-set-the-character-class)
    - [13.5.1 Simple character classes](#13-5-1-simple-character-classes)
    - [13.5.2 Ranges inside character classes](#13-5-2-ranges-inside-character-classes)
    - [13.5.3 Combining ranges and characters](#13-5-3-combining-ranges-and-characters)
    - [13.5.4 Negated character classes](#13-5-4-negated-character-classes)
    - [13.5.5 Special characters inside a character class](#13-5-5-special-characters-inside-a-character-class)
- [13.6 Where should the match occur: anchors](#13-6-where-should-the-match-occur-anchors)
- [13.7 How many times should it repeat: quantifiers](#13-7-how-many-times-should-it-repeat-quantifiers)
    - [Quantifiers with `\d`](#quantifiers-with-d)
    - [Example 1: `\d`, `\d+`, `\d{2}` and `\d\d\d` compared](#example-1-d-d-d-2-and-d-d-d-compared)
- [13.8 How patterns are grouped, combined or interpreted](#13-8-how-patterns-are-grouped-combined-or-interpreted)
- [13.9 Matching, consuming and capturing](#13-9-matching-consuming-and-capturing)
    - [13.9.1 The three actions](#13-9-1-the-three-actions)
    - [13.9.2 The cursor and consumption](#13-9-2-the-cursor-and-consumption)
    - [13.9.3 Consuming mode and static mode](#13-9-3-consuming-mode-and-static-mode)
    - [13.9.4 Why anchors are called "zero-width assertions"](#13-9-4-why-anchors-are-called-zero-width-assertions)
    - [13.9.5 Partial and full consumption](#13-9-5-partial-and-full-consumption)
- [Part B: The re module](#part-b-the-re-module)
- [13.10 The re module](#13-10-the-re-module)
- [13.11 The Pattern and the Match objects](#13-11-the-pattern-and-the-match-objects)
    - [13.11.1 What a Pattern object is](#13-11-1-what-a-pattern-object-is)
    - [Example 2: re.compile() returns a Pattern object](#example-2-re-compile-returns-a-pattern-object)
    - [Try it: you cannot create a Pattern object directly](#try-it-you-cannot-create-a-pattern-object-directly)
    - [13.11.2 What a Match object is](#13-11-2-what-a-match-object-is)
    - [13.11.3 Why these two objects matter](#13-11-3-why-these-two-objects-matter)
- [13.12 The functions of the re module](#13-12-the-functions-of-the-re-module)
    - [13.12.1 Factory function: re.compile()](#13-12-1-factory-function-re-compile)
    - [13.12.2 Convenience functions](#13-12-2-convenience-functions)
    - [Example 3: Approach 1, the convenience function re.match()](#example-3-approach-1-the-convenience-function-re-match)
    - [Example 4: Approach 2, a compiled Pattern object](#example-4-approach-2-a-compiled-pattern-object)
    - [13.12.3 Utility functions](#13-12-3-utility-functions)
    - [Example 5: re.escape()](#example-5-re-escape)
    - [13.12.4 Wrapper functions](#13-12-4-wrapper-functions)
    - [Example 6: The two ways of writing the same thing](#example-6-the-two-ways-of-writing-the-same-thing)
    - [13.12.5 Instance methods](#13-12-5-instance-methods)
    - [13.12.6 Eight operations, two forms](#13-12-6-eight-operations-two-forms)
    - [13.12.7 The five categories, side by side](#13-12-7-the-five-categories-side-by-side)
- [13.13 A brief discussion about groups](#13-13-a-brief-discussion-about-groups)
    - [Example 7: Capturing only what you need](#example-7-capturing-only-what-you-need)
- [13.14 A script using the convenience functions](#13-14-a-script-using-the-convenience-functions)
    - [Example 8: The eight convenience functions in one script](#example-8-the-eight-convenience-functions-in-one-script)
    - [Notes on Example 8](#notes-on-example-8)
- [13.15 A script using the instance methods of a Pattern object](#13-15-a-script-using-the-instance-methods-of-a-pattern-objec)
    - [Example 9: The same eight operations, as Pattern methods](#example-9-the-same-eight-operations-as-pattern-methods)
    - [13.15.1 The match() and search() methods](#13-15-1-the-match-and-search-methods)
    - [Example 10: Guarding against None](#example-10-guarding-against-none)
- [13.16 The attributes of a Pattern object](#13-16-the-attributes-of-a-pattern-object)
    - [Example 11: The four attributes at a glance](#example-11-the-four-attributes-at-a-glance)
    - [Example 12: The same four attributes, one at a time](#example-12-the-same-four-attributes-one-at-a-time)
    - [13.16.1 Using flags to change how matching works](#13-16-1-using-flags-to-change-how-matching-works)
    - [Try it: three flags in action](#try-it-three-flags-in-action)
    - [Try it: reading the flags of a compiled pattern](#try-it-reading-the-flags-of-a-compiled-pattern)
- [13.17 The methods of a Match object](#13-17-the-methods-of-a-match-object)
    - [13.17.1 The core methods](#13-17-1-the-core-methods)
    - [Example 13: The core methods of a Match object](#example-13-the-core-methods-of-a-match-object)
    - [13.17.2 More about group()](#13-17-2-more-about-group)
    - [13.17.3 Named groups and groupdict()](#13-17-3-named-groups-and-groupdict)
    - [Try it: reaching a group by number and by name](#try-it-reaching-a-group-by-number-and-by-name)
    - [Example 14: group() with several arguments](#example-14-group-with-several-arguments)
    - [13.17.4 Position and span methods](#13-17-4-position-and-span-methods)
- [13.18 The attributes of a Match object](#13-18-the-attributes-of-a-match-object)
    - [13.18.1 Match objects are true](#13-18-1-match-objects-are-true)
- [13.19 The attributes of a Pattern object and a Match object compared](#13-19-the-attributes-of-a-pattern-object-and-a-match-object-)
- [13.20 Greedy and non-greedy quantifiers](#13-20-greedy-and-non-greedy-quantifiers)
    - [Example 15: Greedy and lazy, on two examples](#example-15-greedy-and-lazy-on-two-examples)
- [Part C: Advanced topics](#part-c-advanced-topics)
- [13.21 The regex parenthesis family](#13-21-the-regex-parenthesis-family)
- [13.22 Capturing and non-capturing groups](#13-22-capturing-and-non-capturing-groups)
    - [Try it: the same pattern, with and without capturing](#try-it-the-same-pattern-with-and-without-capturing)
    - [Example 16: Four uses of non-capturing groups](#example-16-four-uses-of-non-capturing-groups)
- [13.23 Backreferences](#13-23-backreferences)
    - [13.23.1 Using a backreference to swap two words](#13-23-1-using-a-backreference-to-swap-two-words)
    - [Try it: swapping two adjacent words](#try-it-swapping-two-adjacent-words)
    - [Example 17: Reordering "LastName, FirstName"](#example-17-reordering-lastname-firstname)
- [13.24 The role of parentheses](#13-24-the-role-of-parentheses)
- [13.25 Removing consecutive duplicate words](#13-25-removing-consecutive-duplicate-words)
    - [Example 18: Cleaning repeated words out of a sentence](#example-18-cleaning-repeated-words-out-of-a-sentence)
- [13.26 Lookarounds](#13-26-lookarounds)
    - [13.26.1 Using a lookaround to validate a password](#13-26-1-using-a-lookaround-to-validate-a-password)
    - [Example 19: Password validation with lookaheads](#example-19-password-validation-with-lookaheads)
    - [Example 20: The same check without lookarounds](#example-20-the-same-check-without-lookarounds)
    - [13.26.2 Lookarounds and the overlapping ("banana") problem](#13-26-2-lookarounds-and-the-overlapping-banana-problem)
    - [Example 21: Finding overlapping matches](#example-21-finding-overlapping-matches)
    - [13.26.3 Lookbehinds](#13-26-3-lookbehinds)
    - [Example 22: A positive lookbehind for titles](#example-22-a-positive-lookbehind-for-titles)
- [Scripting questions and assignments](#scripting-questions-and-assignments)
    - [Example 23: Testing for a prime number with a regular expression](#example-23-testing-for-a-prime-number-with-a-regular-express)
- [Beyond the Book](#beyond-the-book)
    - [Extracting structured data with named groups](#extracting-structured-data-with-named-groups)
    - [Replacing with a function](#replacing-with-a-function)
    - [Writing a long pattern readably with re.X](#writing-a-long-pattern-readably-with-re-x)
    - [A caution about findall() and groups](#a-caution-about-findall-and-groups)

## <a name="learning-objectives"></a>Learning objectives

By the end of this chapter you should be able to:

- say where regular expressions are useful: validating, searching, replacing and splitting;
- use character specifiers, character classes, metacharacters and the shorthands `\d`, `\w` and `\s`;
- use anchors and boundaries (`^`, `$`, `\b`, `\A`, `\Z`) to control **where** a match may happen;
- use quantifiers (`*`, `+`, `?`, `{m,n}`) to control **how many times** something repeats;
- group, alternate and escape, so that patterns can be combined and read clearly;
- tell matching, consuming and capturing apart, and understand the cursor and zero-width assertions;
- explain the Pattern object and the Match object, and the place of `re.compile()`;
- use the main `re` functions and Pattern methods: `match()`, `search()`, `findall()`, `finditer()`, `sub()`, `split()`;
- use the Match object's methods and attributes: `group()`, `groups()`, `groupdict()`, `start()`, `end()`, `span()`;
- tell greedy from non-greedy matching, and use regular expressions for extraction, validation and text processing.

**A note from the author.** This chapter is in three parts: (A) a general discussion of regular expressions, (B) the `re` module of Python, and (C) some advanced topics.

[Back to the Table of Contents](#toc)

## <a name="part-a-a-general-discussion-of-regular-expressions"></a>Part A: A general discussion of regular expressions

## <a name="13-1-introduction"></a>13.1 Introduction

Regular expressions are also called REs, regexes or regex patterns. They are used for matching patterns. With them you can ask and answer questions such as "does this string match the given pattern?" or "is there a match for the pattern anywhere in the string?". You can also use them to change a string, or to split it in various ways.

[Back to the Table of Contents](#toc)

## <a name="13-2-the-concept-of-a-regular-expression"></a>13.2 The concept of a regular expression

A regular expression describes a pattern of text. Regexes are used for four main purposes:

| No. | Purpose | Example |
|---|---|---|
| 1 | **Validation or checking** | Is this a valid email address, phone number, or PIN code? Does it have an `@` in it? |
| 2 | **Searching** | Find a fixed word, or a word with variants, such as "colour" in British English and "color" in American English |
| 3 | **Searching and replacing** | Clean data, format text, correct spelling |
| 4 | **Splitting strings** | Split on a pattern rather than on one fixed character |

[Back to the Table of Contents](#toc)

## <a name="13-3-what-a-regular-expression-is"></a>13.3 What a regular expression is

A regular expression is a special sequence of characters that helps you match or find other strings. Every pattern answers five basic questions:

| No. | Question | What answers it |
|---|---|---|
| 1 | What individual character should be matched? | Character specifiers: `a`, `\d`, `.` |
| 2 | Which single character from a set or group? | Character classes: `[a-z]`, `[^0-9]` |
| 3 | Where should it appear? | Anchors: `^`, `$`, `\b` |
| 4 | How many times should it repeat? | Quantifiers: `*`, `+`, `?`, `{m,n}` |
| 5 | How are patterns grouped, combined or interpreted? | Grouping, alternation and escaping: `( )`, `\|`, `\` |

![The five questions every regex pattern answers](https://raw.githubusercontent.com/ag999git/001-Python-book-2026/main/resources/ch-13-nb-01-five-questions.png)

[Back to the Table of Contents](#toc)

## <a name="13-4-character-specifiers-what-to-match"></a>13.4 Character specifiers: what to match

Character specifiers answer the question "which characters do I want to match?". They come in two kinds:

- **A. Single characters**, which are again of two kinds: (1) characters that match themselves, and (2) characters that match something other than themselves.
- **B. Character classes**, discussed in section 13.5.

[Back to the Table of Contents](#toc)

### <a name="13-4-1-characters-that-match-themselves"></a>13.4.1 Characters that match themselves

These are ordinary characters, called **literal characters**. The letter `a` in a pattern matches the letter `a` in the text. Nothing special happens.

[Back to the Table of Contents](#toc)

### <a name="13-4-2-special-characters-that-match-something-other-than-th"></a>13.4.2 Special characters that match something other than themselves

These are the **metacharacters**. They exist so that you can (1) avoid writing very long patterns, and (2) match **kinds** of characters instead of specific ones.

The full list of metacharacters in Python is:

| Name | Symbol |
|---|---|
| Period | `.` |
| Caret | `^` |
| Asterisk | `*` |
| Dollar | `$` |
| Plus | `+` |
| Question mark | `?` |
| Curly braces | `{ }` |
| Square brackets | `[ ]` |
| Backslash | `\` |
| Pipe (vertical bar) | `\|` |
| Parentheses | `( )` |

Three of them deserve a closer look.

**1. Square brackets `[ ]`** create a **character class**: a set of characters you are willing to match. `[abc]` matches `a`, `b` or `c`, and is the same as `[a-c]`. For lowercase letters you would write `[a-z]`. As an example, the pattern `a[bc][de]f` matches `abdf`, `acdf`, `abef` and `acef`.

**2. The caret `^`** is used in two ways:

- **Inside a character class**, as the first character, it means "not": `[^aeiou]` is any character that is not a vowel, and `[^0-9]` is any non-digit.
- **Outside a character class**, it is an anchor meaning "at the beginning". `^Tom` matches "Tom went" but not "Please call Tom", because the second string does not begin with Tom.

**3. The backslash `\`** also has two uses:

- It **escapes** a metacharacter, so that the character matches itself: `\[` matches a real square bracket, and `\\` matches a real backslash.
- It starts a **shorthand** for a common set of characters:

| Shorthand | Matches | Same as |
|---|---|---|
| `\d` | Any decimal digit | `[0-9]` |
| `\D` | Any non-digit | `[^0-9]` |
| `\s` | Any whitespace character | `[ \t\n\r\f\v]` |
| `\S` | Any non-whitespace character | `[^ \t\n\r\f\v]` |
| `\w` | Any "word" character: letters, digits and the underscore | `[a-zA-Z0-9_]` |
| `\W` | Any non-word character | `[^a-zA-Z0-9_]` |

**Escaping.** Sometimes you want a special character to lose its power and match itself. A period normally means "any character"; `\.` means a real full stop. Putting a backslash before a special character is called **escaping**.

[Back to the Table of Contents](#toc)

## <a name="13-5-which-single-character-from-a-set-the-character-class"></a>13.5 Which single character from a set: the character class

A **character class** lets you choose one character from a set. It always matches **exactly one** character, never more. It answers the question "which one character is allowed at this position?". Character classes are written inside square brackets: `[ ... ]`.

There are five kinds:

[Back to the Table of Contents](#toc)

### <a name="13-5-1-simple-character-classes"></a>13.5.1 Simple character classes

`[abc]` matches `a`, `b` or `c`. The order does not matter.

[Back to the Table of Contents](#toc)

### <a name="13-5-2-ranges-inside-character-classes"></a>13.5.2 Ranges inside character classes

A hyphen makes a range.

| No. | Pattern | Meaning | Shorthand | Matches | Does not match |
|---|---|---|---|---|---|
| 1 | `[a-z]` | Any lowercase letter | | `g`, `z` | `G`, `5`, `!` |
| 2 | `[A-Z]` | Any uppercase letter | | `R`, `B` | `r`, `9`, `#` |
| 3 | `[0-9]` | Any digit | `\d` | `4`, `0` | `a`, `?`, `_` |
| 4 | `[a-zA-Z]` | Any letter, upper or lower case | | `m`, `M` | `3`, `.` |
| 5 | `[^0-9]` | Any non-digit | `\D` | `A`, `l` | `7`, `2` |
| 6 | `[a-zA-Z0-9_]` | Any "word" character | `\w` | `x`, `9`, `_` | `&`, `$` |
| 7 | `[^a-zA-Z0-9_]` | Any non-word character | `\W` | `!`, `@` | `f`, `4`, `_` |
| 8 | `[ \t\n\r\f\v]` | Any whitespace | `\s` | space, tab | `k`, `8` |

Two notes on this table:

1. `^` has two different meanings. Outside a class it is an anchor for the start of the string. As the **first** character inside a class it negates the class.
2. The "shorthand" column gives the short alias for a longer class. `\d` is easier to read than `[0-9]`.

[Back to the Table of Contents](#toc)

### <a name="13-5-3-combining-ranges-and-characters"></a>13.5.3 Combining ranges and characters

You can mix ranges and single characters: `[a-zA-Z0-9_]` matches a lowercase letter, an uppercase letter, a digit or an underscore, but only **one** of them.

[Back to the Table of Contents](#toc)

### <a name="13-5-4-negated-character-classes"></a>13.5.4 Negated character classes

When `^` is the **first** character inside the brackets it means "not". `[^aeiou]` matches any character that is not a vowel. Outside the brackets, `^` is an anchor.

[Back to the Table of Contents](#toc)

### <a name="13-5-5-special-characters-inside-a-character-class"></a>13.5.5 Special characters inside a character class

Inside `[ ]` most special characters lose their special meaning.

| Character | Outside the class | Example | Inside the class | Example |
|---|---|---|---|---|
| `.` | Any character | `a.c` matches `abc`, `a1c` | A literal dot | `[.]` matches only `.` |
| `*` | Zero or more times | `a*` matches "", `aaaa` | A literal star | `[*]` matches only `*` |
| `+` | One or more times | `a+` matches `a`, `aaaa` | A literal plus | `[+^]` matches `+` or `^` |
| `?` | Optional (0 or 1) | `ab?` matches `a`, `ab` | A literal question mark | `[?]` matches only `?` |
| `$` | End of string | `x$` matches the x in "tax" | A literal dollar | `[$]` matches only `$` |
| `( )` | Capturing group | `(ab)` saves `ab` | Literal brackets | `[()]` matches `(` or `)` |
| `\|` | Alternation (or) | `a\|b` matches `a` or `b` | A literal pipe | `[\|]` matches only `\|` |
| `^` | Start of string | `^A` matches the A of "Apple" | Negation | `[^a]` matches any non-a |
| `-` | A literal hyphen | `a-b` matches "a-b" | A range | `[a-z]` means a to z |

Three characters still need care inside a class:

| Character | When it is special | When it is literal |
|---|---|---|
| `^` (caret) | Only as the first character: `[^0-9]` | Anywhere else: `[a^b]` |
| `-` (hyphen) | Between two characters: `[a-z]` | At the very start or end: `[-az]`, `[az-]` |
| `\` (backslash) | Always. It escapes, and it starts shorthands | `[\\]` matches one backslash |

Think of square brackets as a safe zone. To match a literal plus or a literal dot you do not need `\+` or `\.`; inside brackets, `[+]` and `[.]` work perfectly.

[Back to the Table of Contents](#toc)

## <a name="13-6-where-should-the-match-occur-anchors"></a>13.6 Where should the match occur: anchors

Anchors answer "where?". They do not match characters; they match **positions** in the string. Think of them as markers in a sentence, not letters.

| Anchor | Meaning |
|---|---|
| `^` | Start of the string (or of a line, with the MULTILINE flag) |
| `$` | End of the string (or of a line) |
| `\b` | Word boundary |
| `\B` | Not a word boundary |
| `\A` | Absolute start of the string |
| `\Z` | Absolute end of the string |

[Back to the Table of Contents](#toc)

## <a name="13-7-how-many-times-should-it-repeat-quantifiers"></a>13.7 How many times should it repeat: quantifiers

| No. | Quantifier | Meaning |
|---|---|---|
| 1 | `*` | The previous item, zero or more times. `spo*n` matches `spn`, `spon`, `spoon`, and so on |
| 2 | `+` | One or more times. `spo+n` does not match `spn`, but matches `spon` and `spoon` |
| 3 | `?` | Once or not at all: the item is optional |
| 4 | `{m}` | Exactly m times |
| 5 | `{m,n}` | At least m times and at most n times, where m is not greater than n. `spo{1,3}n` matches `spon`, `spoon` and `spooon`, but not `spn` or `spoooon`. You may leave out m (a lower limit of 0) or n (no upper limit) |

The three short quantifiers can all be written in the long form: `{0,}` is `*`, `{1,}` is `+`, and `{0,1}` is `?`. The short forms are easier to read.

[Back to the Table of Contents](#toc)

### <a name="quantifiers-with-d"></a>Quantifiers with `\d`

| Pattern | Means | Matches |
|---|---|---|
| `\d` | One digit | Exactly one digit |
| `\d+` | One digit, then as many more as possible | A whole run of consecutive digits |
| `\d{2}` | Two digits | Exactly two consecutive digits |
| `\d\d\d` | Three digits | Exactly three consecutive digits |

[Back to the Table of Contents](#toc)

### <a name="example-1-d-d-d-2-and-d-d-d-compared"></a>Example 1: `\d`, `\d+`, `\d{2}` and `\d\d\d` compared

**What the code does.** It uses `re.findall()`, which returns a list of all the matches in a string, to run four patterns on the text `"My numbers are 1, 234, and 56z7."`.

**How it works.** `findall()` scans from left to right and never reuses a character it has already matched.

| Pattern | Result | Why |
|---|---|---|
| `\d` | `['1','2','3','4','5','6','7']` | Every digit on its own |
| `\d+` | `['1', '234', '56', '7']` | Runs of digits. The `z` breaks 56 and 7 apart |
| `\d{2}` | `['23', '56']` | Exactly two in a row. In 234 it takes 23, and then only 4 is left |
| `\d\d\d` | `['234']` | The only run of three |

**Learning points**

1. A quantifier attaches to the item immediately before it.
2. `\d{2}` does not mean "two-digit numbers". It means "any two digits in a row", which is why 234 gives 23.
3. Matching is greedy by default. `\d+` takes as many digits as it can.

In [1]:
# Using findall() with digit patterns
import re
text = "My numbers are 1, 234, and 56z7."
print(re.findall(r"\d", text))  # ['1','2','3','4','5','6','7']
print(re.findall(r"\d+", text)) # ['1', '234', '56', '7']
print(re.findall(r"\d{2}", text)) # ['23', '56']
print(re.findall(r"\d\d\d", text)) # ['234']


['1', '2', '3', '4', '5', '6', '7']
['1', '234', '56', '7']
['23', '56']
['234']


[Back to the Table of Contents](#toc)

## <a name="13-8-how-patterns-are-grouped-combined-or-interpreted"></a>13.8 How patterns are grouped, combined or interpreted

Three tools let you build bigger patterns out of smaller ones.

**1. Grouping `( )`.** Parentheses bundle part of a pattern. They do three jobs:

- **One unit:** `(abc)+` matches `abc`, `abcabc` and so on, while `abc+` matches `ab` followed by one or more `c`.
- **Quantifiers apply to the whole group.**
- **Data extraction:** groups let you capture and pull out part of a match, such as the domain of an email address.

**2. Alternation `|`.** The pipe is a logical OR: `A|B` matches either A or B. `apple|orange` finds both words. It is often combined with grouping, as in `(July|August) \d{2}`.

**3. Escaping `\`.** To search for a special character itself, put a backslash before it: `\.` for a full stop, `\$` for a dollar sign, `\\` for a backslash.

[Back to the Table of Contents](#toc)

## <a name="13-9-matching-consuming-and-capturing"></a>13.9 Matching, consuming and capturing

**A note from the author.** This topic can look complex at first. If you find it hard, read Part B first and come back to it, or skip it altogether on a first reading.

[Back to the Table of Contents](#toc)

### <a name="13-9-1-the-three-actions"></a>13.9.1 The three actions

When the regex engine works through a string, three different things can happen:

| Action | What it means | The question it answers |
|---|---|---|
| **Matching** | The rule is satisfied | "Does the text in front of me fit the rule?" |
| **Consuming** | The cursor moves forward past the characters that matched, so they cannot be matched again by the next part of the pattern | "How far have I moved?" |
| **Capturing** | Matched text is stored in a numbered slot for later use. This happens only for text inside `( )` | "Which part do I want to keep?" |

These three are closely related but different: some elements match **and** consume; some match without consuming (anchors); some matches are also captured; and a pattern may consume only part of a string and leave the rest alone.

![Matching, consuming and capturing are three different things](https://raw.githubusercontent.com/ag999git/001-Python-book-2026/main/resources/ch-13-nb-02-match-consume-capture.png)

[Back to the Table of Contents](#toc)

### <a name="13-9-2-the-cursor-and-consumption"></a>13.9.2 The cursor and consumption

Think of the cursor as the actor and consumption as the action.

- **The cursor** is an invisible pointer showing where the engine is. It sits **between** characters, not on them. In the string `CAT` there are four cursor positions: `[0] C [1] A [2] T [3]`.
- **Consumption** is moving the cursor forward because a character matched. Once a character is consumed, the engine cannot use it again for this match. (There are exceptions, covered by lookarounds later.)

[Back to the Table of Contents](#toc)

### <a name="13-9-3-consuming-mode-and-static-mode"></a>13.9.3 Consuming mode and static mode

| | 1. Consuming mode: characters | 2. Static mode: anchors |
|---|---|---|
| Examples | `A`, `\w`, `\d`, `.` | `^`, `$`, `\b`, `\A`, `\Z` |
| What the engine does | Checks the character, consumes it, moves the cursor | Checks the position only |
| Effect on `span()` | Increases the end index | No effect |
| Width | Positive | Zero |

For the text `CAT` and the pattern `C`: the C matches, is consumed, and the cursor moves from 0 to 1. For the pattern `^CAT`: the `^` asks "am I at the beginning?"; the answer is yes, but no character is consumed and the cursor does not move. Only then does matching of C, A and T begin.

[Back to the Table of Contents](#toc)

### <a name="13-9-4-why-anchors-are-called-zero-width-assertions"></a>13.9.4 Why anchors are called "zero-width assertions"

- **Zero-width:** width is the number of characters the cursor moves. `\d` has width 1; `^` and `$` have width 0. An anchor matches a **position between characters**, so it takes up no space.
- **Assertion:** an assertion is a test, not a command to grab text. `\d` says "find a digit and eat it". `\b` asks "is this a boundary between a word and a space? If yes, continue; if no, fail".

| Regex element | Consumes characters? | Moves the cursor? | Width |
|---|---|---|---|
| `\d` | Yes | Yes | 1 |
| `\w` | Yes | Yes | 1 |
| `^` | No | No | 0 |
| `$` | No | No | 0 |
| `\b` | No | No | 0 |

[Back to the Table of Contents](#toc)

### <a name="13-9-5-partial-and-full-consumption"></a>13.9.5 Partial and full consumption

A successful match does **not** mean the whole string was processed. The engine consumes only as much as the pattern asks for.

| | Partial consumption | Full consumption |
|---|---|---|
| Example | `re.match(r"\d+", "123 abc")` | `re.match(r"\d+.*", "123 abc")` |
| What happens | 123 matches, is consumed, and the engine stops. The space and `abc` are never touched | `\d+` takes 123, then `.*` takes everything else to the end of the line |

`m.span()` is the definitive record of consumption: it gives `(start, end)`, and everything between those two indexes has been matched and consumed.

| Action | Scope | Rule |
|---|---|---|
| Match | The pattern | Checks whether the text satisfies the rule |
| Consume | The cursor | Moves the cursor across the characters that satisfy the pattern |
| Capture | Memory | Stores consumed text that lies inside `( )` |

Two important points: (1) only consumed text can be captured, and (2) text is captured only if it lies inside parentheses. So `(\d+)` matches, consumes and captures digits, while `\d+` matches and consumes them but does not capture them.

**The key idea:** matching checks, consuming moves, capturing remembers.

[Back to the Table of Contents](#toc)

## <a name="part-b-the-re-module"></a>Part B: The re module

## <a name="13-10-the-re-module"></a>13.10 The re module

A regex is a language for describing patterns; the `re` module is the tool that understands that language. It helps Python find, check, extract or replace text according to those rules. The module is part of the Python standard library, so you do not have to install it. You only have to import it:

```python
import re
```

A few things make the `re` module unusual:

- It is written largely in **C** inside the Python interpreter, so matching is fast.
- Python's regexes belong to the family of **Perl-style** regular expressions, as do those of Java, JavaScript, PHP and C#. Python does not use the PCRE library itself; it has its own engine written in C.

[Back to the Table of Contents](#toc)

## <a name="13-11-the-pattern-and-the-match-objects"></a>13.11 The Pattern and the Match objects

In most libraries you create objects yourself: `obj = SomeClass()`. The `re` module is different. Its two main objects, **Pattern** and **Match**, are created for you:

- `pat = re.compile(r"\d+")` returns a **Pattern** object.
- `m = re.search(r"\d+", "abc 123")` returns a **Match** object.

A Pattern object stores **the rules** of matching. A Match object stores **the result** of applying those rules to one string.

![A Pattern object applied to a string gives a Match object](https://raw.githubusercontent.com/ag999git/001-Python-book-2026/main/resources/ch-13-nb-03-pattern-match.png)

[Back to the Table of Contents](#toc)

### <a name="13-11-1-what-a-pattern-object-is"></a>13.11.1 What a Pattern object is

A Pattern object is a **compiled** regular expression: an object that knows how to match. It is a reusable matching engine. It holds logic and rules, not text.

What a Pattern object does **not** do: (1) it does not store the input text, (2) it does not store match results, (3) it does not say True or False by itself.

A warning about names. The word "pattern" is used in two ways, and they are different things:

| Using the name as a string | Using the name as a compiled object |
|---|---|
| `pattern = "a*b"` | `pattern = re.compile("a*b")` |
| Type: `str` | Type: `re.Pattern` |
| A description of the rules | An active matching engine |
| Passive text | Has methods: `match()`, `search()` ... |

[Back to the Table of Contents](#toc)

### <a name="example-2-re-compile-returns-a-pattern-object"></a>Example 2: re.compile() returns a Pattern object

**What the code does.** It compiles the pattern `a*b` and prints the type of the result.

**Learning points**

1. `re.compile()` is a **factory function**: you give it text and it gives you back an object.
2. `type(p)` prints `<class 're.Pattern'>`, which proves that `p` is a compiled regex, not a string.
3. The pattern `a*b` means "zero or more `a`, then one `b`", so it matches `b`, `ab`, `aab`, and so on.

In [2]:
import re
# Factory function re.compile() takes a regex pattern string and returns
# a compiled regex Pattern object.

p = re.compile("a*b")
print(type(p))  # Output: <class 're.Pattern'>
# Output shows that p is indeed a compiled regex object.


<class 're.Pattern'>


[Back to the Table of Contents](#toc)

### <a name="try-it-you-cannot-create-a-pattern-object-directly"></a>Try it: you cannot create a Pattern object directly

This cell is not in the book. The book says that `re.Pattern("a*b")` is an error, and that you must use the factory function. This cell proves it, with the error caught so that the notebook can carry on.

In [3]:
import re

try:
    p = re.Pattern("a*b")          # not allowed
except TypeError as e:
    print("TypeError:", e)

p = re.compile("a*b")              # the correct way
print("This works:", type(p))

TypeError: cannot create 're.Pattern' instances
This works: <class 're.Pattern'>


[Back to the Table of Contents](#toc)

### <a name="13-11-2-what-a-match-object-is"></a>13.11.2 What a Match object is

A Match object represents three things: (1) the result of a successful match, (2) the part of the string that matched, and (3) where it matched. It is created **only if the match succeeds**. It records what happened, not the rules.

What a Match object does **not** do: (1) it does not perform matching, (2) it does not store the regex rules, and (3) it does not exist if the match failed. In that case you get `None`.

[Back to the Table of Contents](#toc)

### <a name="13-11-3-why-these-two-objects-matter"></a>13.11.3 Why these two objects matter

The `re` module uses five kinds of functions and methods, and they differ in what they create and what they return. Some internally create a Pattern object and use it at once; others work on a Pattern object you have already made; and others return a Match object. Knowing which is which is the key to reading `re` code.

[Back to the Table of Contents](#toc)

## <a name="13-12-the-functions-of-the-re-module"></a>13.12 The functions of the re module

![The five kinds of functions and methods in the re module](https://raw.githubusercontent.com/ag999git/001-Python-book-2026/main/resources/ch-13-nb-04-five-categories.png)

[Back to the Table of Contents](#toc)

### <a name="13-12-1-factory-function-re-compile"></a>13.12.1 Factory function: re.compile()

A **factory function** creates and returns an object. In the `re` module the factory function is `compile()`, which returns a Pattern object:

```python
re.compile(pattern)
```

What it does: (1) takes a regex pattern, (2) builds an internal regex engine, and (3) returns a Pattern object. It is used when (1) the same pattern is applied many times, (2) the pattern is used inside a loop, and (3) you want to keep the compiled Pattern object for reuse.

Advantages of a factory function: (1) the user does not have to build the object, (2) the library can change the class without breaking user code, and (3) the factory checks for errors early, so a bad pattern is reported at once. The disadvantages: (1) the return type is not obvious from the call, and (2) it hides complexity, which can make the logic harder to follow.

**Why you cannot write `re.Pattern("a*b")`.** `re.Pattern` is a built-in extension type, defined in C. It has no public constructor, because building a compiled regex takes a real compilation step. So the class is a "result" type, not a blueprint you build from. Think of a car factory: `re.compile(r"a*b")` is the factory, and the Pattern object is the car. You never build the car yourself, but once you have it you can drive it: `p.match()`, `p.search()`.

[Back to the Table of Contents](#toc)

### <a name="13-12-2-convenience-functions"></a>13.12.2 Convenience functions

A **convenience function** is a shortcut that (1) saves typing, (2) hides the creation of the object, and (3) combines steps. Examples: `re.match()`, `re.fullmatch()`, `re.search()`, `re.findall()`.

So `re.match(pattern, string)` does the same work as `re.compile(pattern).match(string)`.

They are best for (1) one-time matching, (2) simple scripts, and (3) quick checks. Their limitation: the pattern is compiled again every time you call them, so they are less efficient when the same pattern is used repeatedly.

In the table below, `p` is the pattern, `s` is the string, and `r` is the replacement text.

| No. | Function | Use | Do not use it for | Returns |
|---|---|---|---|---|
| 1 | `re.match(p, s)` | Match at the start | Searching inside a string | Match or None |
| 2 | `re.fullmatch(p, s)` | Match the whole string | A partial match | Match or None |
| 3 | `re.search(p, s)` | Find anywhere | Start-only checks | Match or None |
| 4 | `re.findall(p, s)` | Find all matches | When you need the Match objects | list |
| 5 | `re.finditer(p, s)` | Iterate over matches | When you expect a list | iterator |
| 6 | `re.split(p, s)` | Split a string | When you expect a Match | list |
| 7 | `re.sub(p, r, s)` | Replace | Counting | str |
| 8 | `re.subn(p, r, s)` | Replace and count | A simple replacement | (str, int) |

**Why convenience functions are not called factory functions.** Some of them do return objects, but they never hand you a reusable Pattern. They (1) compile the pattern temporarily, (2) apply it at once, and (3) return the result. A Match object is tied to one string and one run, so it cannot be reused; a Pattern object is general-purpose and reusable.

[Back to the Table of Contents](#toc)

### <a name="example-3-approach-1-the-convenience-function-re-match"></a>Example 3: Approach 1, the convenience function re.match()

**What the code does.** It calls `re.match(r'\d+', text)` on `"123 def 456"` and prints the Match object.

**The steps.** (1) You pass a pattern string to `re.match()`. (2) Python compiles it internally. (3) The compiled pattern is used at once. (4) A Match object is returned. (5) That compiled pattern is not saved or reused.

**Learning points**

1. `re.match()` looks only at the **start** of the string, so it finds 123, not 456.
2. Printing a Match object shows its `span` (here `(0, 3)`) and the text it matched.
3. In the f-string the pattern is written `r'\\d+'`, with two backslashes, because an f-string would otherwise treat `\d` as an escape sequence. The output shows a single backslash.

In [4]:
text = "123 def 456"
match_obj = re.match(r'\d+', text)  # Using re.match directly
print(f"re.match(r'\\d+', '{text}') -> {match_obj}")
# Output: <re.Match object; span=(0, 3), match='123'>


re.match(r'\d+', '123 def 456') -> <re.Match object; span=(0, 3), match='123'>


[Back to the Table of Contents](#toc)

### <a name="example-4-approach-2-a-compiled-pattern-object"></a>Example 4: Approach 2, a compiled Pattern object

**What the code does.** It compiles `r"\d+"` into `pattern_digits` and then calls `.match(text)` on that object.

**The steps.** (1) `re.compile()` creates a Pattern object. (2) It is stored in a variable. (3) `.match(text)` uses the already compiled pattern. (4) A Match object is returned. (5) The same Pattern can be used again on other strings.

**Why it matters.** The result is identical to Example 3. The difference is efficiency and control: compile once, use many times.

**Learning points**

1. The pattern is compiled **explicitly**, so you can see what is happening.
2. It is reusable, which is good in loops and repeated checks.
3. It takes one more line of code, and gives you more control.

![Two ways to run the same regex operation, with the same result](https://raw.githubusercontent.com/ag999git/001-Python-book-2026/main/resources/ch-13-nb-05-two-ways.png)

In [5]:
import re
text = "123 def 456"
pattern_digits = re.compile(r"\d+")  # Pattern to match one/ more digits
match_obj_compiled = pattern_digits.match(text)  # Using compiled pattern
print(f"pattern_digits.match('{text}') -> {match_obj_compiled}")
# Output: <re.Match object; span=(0, 3), match='123'>


pattern_digits.match('123 def 456') -> <re.Match object; span=(0, 3), match='123'>


[Back to the Table of Contents](#toc)

### <a name="13-12-3-utility-functions"></a>13.12.3 Utility functions

A **utility function** does a small supporting job. It helps the main work without doing it: it does not match text itself. The main one in the `re` module is `re.escape()`.

**What `re.escape()` does.** Suppose a user types `a+b` and you want to match that text exactly. In a regex, `+` means "one or more", so `re.fullmatch("a+b", "a+b")` fails: the engine reads the pattern as "one or more `a` followed by `b`". `re.escape()` turns the special characters into ordinary ones by putting a backslash in front of them.

`re.escape()` is useful for (1) matching user input literally, (2) searching for literal strings, (3) preventing unwanted regex interpretation, and (4) preparing text before a regex operation. It matters most when the input may contain `+ * ? . ( ) [ ] { } ^ $`.

What it does **not** do: it does not match, validate, compile or search. It only prepares text.

[Back to the Table of Contents](#toc)

### <a name="example-5-re-escape"></a>Example 5: re.escape()

**What the code does.** It escapes the text `"a+b"` and prints the result, then uses the escaped pattern with `re.fullmatch()`.

**Learning points**

1. `re.escape("a+b")` gives `a\+b`. The plus now means a real plus sign.
2. `re.fullmatch()` then succeeds and prints a Match object with `span=(0, 3)`.
3. Without escaping, the same call returns `None`.

In [6]:
import re
safe_pattern = re.escape("a+b")
print(safe_pattern)  # Output: a\+b
# re.escape() function takes string "a+b" & escapes the special character "+"
# by adding a backslash before it, resulting in the escaped string "a\+b".
print(re.fullmatch(safe_pattern, "a+b")) # Success
# Output: <re.Match object; span=(0, 3), match='a+b'>


a\+b
<re.Match object; span=(0, 3), match='a+b'>


[Back to the Table of Contents](#toc)

### <a name="13-12-4-wrapper-functions"></a>13.12.4 Wrapper functions

A **wrapper function** calls another function inside itself and hides the extra steps. `re.match()` is a good example: internally it uses `Pattern.match()`, and it hides the creation of the Pattern object.

Conceptually, `re.match()` behaves like this:

```python
def match(pattern, string):
    return re.compile(pattern).match(string)
```

So (1) the pattern is compiled, (2) a temporary Pattern object is created, and (3) the `match()` method of that object is called. You never see those steps.

![What re.match() does behind the scenes](https://raw.githubusercontent.com/ag999git/001-Python-book-2026/main/resources/ch-13-nb-06-wrapper.png)

[Back to the Table of Contents](#toc)

### <a name="example-6-the-two-ways-of-writing-the-same-thing"></a>Example 6: The two ways of writing the same thing

**What the code does.** It shows the long way (compile, then call the method) and the short way (one call to `re.match()`), with the same result. The cell prints nothing; it only defines `pattern` and `result`.

**Learning points**

1. `re.match()` is both a **wrapper** function (it hides `Pattern.match()`) and a **convenience** function (it is shorter and easier).
2. "Wrapper" describes **how** it works inside; "convenience" describes **why** it exists.
3. The same idea applies to `re.search()`, `re.fullmatch()`, `re.findall()` and `re.finditer()`.

In [7]:
# For example, instead of writing:
pattern = re.compile(r"\d+")
result = pattern.match(text)
# we can simply write:
result = re.match(r"\d+", text)
# Thus, re.match() provides a simpler interface.


[Back to the Table of Contents](#toc)

### <a name="13-12-5-instance-methods"></a>13.12.5 Instance methods

An **instance method** belongs to an object and works on the data inside it. In the `re` module the instance methods belong to the Pattern object, so you must first create one with `re.compile()`. Then you may call `p.match()`, `p.fullmatch()`, `p.search()`, `p.findall()`, `p.finditer()`, `p.split()`, `p.sub()` and `p.subn()`.

Why use them? (1) The pattern is already compiled, (2) it is not compiled again and again, and (3) this is more efficient when the same regex is used many times, for example inside a loop:

```python
pattern = re.compile(r"\d+")
for text in texts:            # texts is a list of strings to search through
    result = pattern.search(text)
```

| Convenience function | Instance method |
|---|---|
| Compiles internally | Uses an already compiled pattern |
| Shorter and simpler | Better for repeated use |
| Hides the Pattern object | Uses the Pattern object openly |

[Back to the Table of Contents](#toc)

### <a name="13-12-6-eight-operations-two-forms"></a>13.12.6 Eight operations, two forms

Nearly every regex operation exists in both forms. They do the same work; only the way the pattern is supplied differs.

| No. | Operation | Convenience function | Pattern instance method | Returns |
|---|---|---|---|---|
| 1 | Match at start | `re.match(p, s)` | `p.match(s)` | Match or None |
| 2 | Match whole string | `re.fullmatch(p, s)` | `p.fullmatch(s)` | Match or None |
| 3 | Search anywhere | `re.search(p, s)` | `p.search(s)` | Match or None |
| 4 | Find all (list) | `re.findall(p, s)` | `p.findall(s)` | list |
| 5 | Find all (iterator) | `re.finditer(p, s)` | `p.finditer(s)` | iterator |
| 6 | Split | `re.split(p, s)` | `p.split(s)` | list |
| 7 | Substitute | `re.sub(p, r, s)` | `p.sub(r, s)` | str |
| 8 | Substitute and count | `re.subn(p, r, s)` | `p.subn(r, s)` | tuple |

[Back to the Table of Contents](#toc)

### <a name="13-12-7-the-five-categories-side-by-side"></a>13.12.7 The five categories, side by side

| Type | Example | Creates a Pattern object? | Main purpose |
|---|---|---|---|
| Factory | `re.compile()` | Yes | Create a Pattern |
| Convenience | `re.match()` | No | Quick use |
| Utility | `re.escape()` | No | Helper task |
| Wrapper | `re.match()` | No | Delegates the work |
| Instance method | `pattern.match()` | No | Object-based work |

[Back to the Table of Contents](#toc)

## <a name="13-13-a-brief-discussion-about-groups"></a>13.13 A brief discussion about groups

Think of a regex as a search filter, and of capturing groups, the round brackets, as highlighters. Without groups, a match is one big blob of text. Groups let you slice that blob automatically.

Suppose the matched text is `123 def 456`. Without groups you get one complete match. With groups you can pull out 123, or def, or 456 separately.

**A rule of thumb.** Put `( )` only around the data you want to extract. Leave the navigation text (spaces, separators, punctuation, filler) outside the brackets if you do not want to keep it.

[Back to the Table of Contents](#toc)

### <a name="example-7-capturing-only-what-you-need"></a>Example 7: Capturing only what you need

**What the code does.** On the text `"abc 123 def 456"` it runs two patterns:

| Pattern | Groups | What is captured |
|---|---|---|
| `(\d+)\D+(\d+)` | 2 | Only the two runs of digits. The text between them is matched but not kept |
| `(\d+)(\D+)(\d+)` | 3 | The digits **and** the text between them |

**How it works.** `\D` is the opposite of `\d`: any non-digit. In the first pattern `\D+` is outside the brackets, so it is matched and consumed but not captured. In the second it is inside brackets, so it becomes group 2.

**Learning points**

1. `m.group(1)` is the first group, `m.group(2)` the second, and so on. `m.group(0)` is the whole match.
2. Group numbers are decided by the order of the **opening** brackets.
3. In the second pattern, group 2 is `" def "` with the spaces included.

In [8]:
import re
text = "abc 123 def 456"

# Example 1: Capture ONLY the two digit sequences. Ignore text between them.
# The pattern is r"(\d+)\D+(\d+)".
# (\d+) captures first sequence of digits (the first group),
# \D+ matches space & "def" between "123" & "456". Does not capture them as group.
# (\d+) matches and captures the second sequence of digits (456) (the second group).

m1 = re.search(r"(\d+)\D+(\d+)", text)
print("First digits :", m1.group(1))   # 123
print("Second digits:", m1.group(2))   # 456

# Example 2: Capture digits + intervening text + digits
# The pattern is r"(\d+)(\D+)(\d+)".
# (\d+) captures first sequence of digits (123) (group 1)
# (\D+) captures space & "def" between "123" & "456" (group 2)
# (\d+) captures second sequence of digits (456) (group 3)

m2 = re.search(r"(\d+)(\D+)(\d+)", text)
print("First digits :", m2.group(1))   # 123
print("Non-digits   :", m2.group(2))   # " def "
print("Second digits:", m2.group(3))   # 456


First digits : 123
Second digits: 456
First digits : 123
Non-digits   :  def 
Second digits: 456


[Back to the Table of Contents](#toc)

## <a name="13-14-a-script-using-the-convenience-functions"></a>13.14 A script using the convenience functions

### <a name="example-8-the-eight-convenience-functions-in-one-script"></a>Example 8: The eight convenience functions in one script

**What the code does.** On the text `"abc 123 def 456"` it calls all eight convenience functions in turn, printing the result of each. The comments in the code say what each function does, and the comment under each `print()` shows the expected output.

**How it works.**

| Function | Question it answers | Result here |
|---|---|---|
| `re.match(r"abc", text)` | Does the string **start** with abc? | A Match, span (0, 3) |
| `re.fullmatch(...)` | Does the **whole** string match? | A Match, span (0, 15) |
| `re.search(r"123", text)` | Is 123 **anywhere**? | A Match, span (4, 7) |
| `re.findall(r"\d+", text)` | All runs of digits, as text | `['123', '456']` |
| `re.finditer(r"\d+", text)` | All runs of digits, as Match objects | Two objects, with positions 4 and 12 |
| `re.split(r"\s+", text)` | Split on whitespace | `['abc', '123', 'def', '456']` |
| `re.sub(r"\d+", "#", text)` | Replace digits | `abc # def #` |
| `re.subn(r"\d+", "#", text)` | Replace and count | `('abc # def #', 2)` |

**Learning points**

1. `findall()` gives you the **text**; `finditer()` gives you Match objects, so you also get positions with `match.start()` and `match.span()`.
2. `sub()` returns only the new string; `subn()` returns a tuple of the new string and the number of replacements.
3. This cell prints a `SyntaxWarning` about `\d`. It comes from the line `print("re.finditer(r'\d+', text):")`, where the pattern is inside an **ordinary** string, not a raw one. The code still works. Writing `print(r"re.finditer(r'\d+', text):")` removes the warning.

In [9]:
import re

# Sample text used for all examples
text = "abc 123 def 456"

# 1. re.match()
# Tries to match the pattern ONLY at the beginning of the string
result = re.match(r"abc", text)  # Match 'abc' at start
print(f"Match {r'abc'} With {text}-> {result}")
# Match abc With abc 123 def 456-> <re.Match object; span=(0, 3), match='abc'>

# 2. re.fullmatch()
# Matches the pattern against the ENTIRE string
result = re.fullmatch(r"abc 123 def 456", text) #Fullmatch entire string
print(f"Fullmatch {r'abc 123 def 456'} With {text}-> {result}")
# Fullmatch abc 123 def 456 With abc 123 def 456-> <re.Match object; span=(0, 15),           match='abc 123 def 456'>

# 3. re.search()
# Searches for the pattern ANYWHERE in the string
result = re.search(r"123", text)  # Search for '123'
print(f"Search {r'123'} In {text}-> {result}")
# Search 123 In abc 123 def 456-> <re.Match object; span=(4, 7), match='123'>

# 4. re.findall()
# Finds ALL matches and returns them as a LIST
# r"\d+" matches sequences of digits
result = re.findall(r"\d+", text)  # Find all digit sequences
print(f"Findall {r'\d+'} In {text}-> {result}")
# Findall \d+ In abc 123 def 456-> ['123', '456']

# 5. re.finditer()
# Finds ALL matches and returns an ITERATOR
# Each item is a Match object
print("re.finditer(r'\d+', text):")
for match in re.finditer(r"\d+", text):  # Iterate over all matches
    print("Match:", match.group(), "at position", match.start())
# Match: 123 at position 4
# Match: 456 at position 12

# 6. re.split()
# Splits the string wherever the pattern matches
# r"\s+" matches one or more whitespace characters
result = re.split(r"\s+", text)  # Split on whitespace
print(f"Split {r'\s+'} In {text}-> {result}")
# Split \s+ In abc 123 def 456-> ['abc', '123', 'def', '456']

# 7. re.sub()
# Replaces ALL matches with a new value
result = re.sub(r"\d+", "#", text)  # Replace digit sequences with '#'
print(f"Sub {r'\d+'} With '#' In {text}-> {result}")
# Sub \d+ With '#' In abc 123 def 456-> abc # def #

# 8. re.subn()
# Same as sub(), but ALSO returns the count of replacements
result = re.subn(r"\d+", "#", text)  # Replace digit sequences with '#' and get count
print(f"Subn {r'\d+'} With '#' In {text}-> ", result)
# Subn \d+ With '#' In abc 123 def 456->  ('abc # def #', 2)


Match abc With abc 123 def 456-> <re.Match object; span=(0, 3), match='abc'>
Fullmatch abc 123 def 456 With abc 123 def 456-> <re.Match object; span=(0, 15), match='abc 123 def 456'>
Search 123 In abc 123 def 456-> <re.Match object; span=(4, 7), match='123'>
Findall \d+ In abc 123 def 456-> ['123', '456']
re.finditer(r'\d+', text):
Match: 123 at position 4
Match: 456 at position 12
Split \s+ In abc 123 def 456-> ['abc', '123', 'def', '456']
Sub \d+ With '#' In abc 123 def 456-> abc # def #
Subn \d+ With '#' In abc 123 def 456->  ('abc # def #', 2)


<>:34: SyntaxWarning: invalid escape sequence '\d'
<>:34: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_687/3856532202.py:34: SyntaxWarning: invalid escape sequence '\d'
  print("re.finditer(r'\d+', text):")


[Back to the Table of Contents](#toc)

### <a name="notes-on-example-8"></a>Notes on Example 8

- **`re.finditer()` deserves a second look.** It scans the whole string, finds all non-overlapping matches, and returns an **iterator**: it produces Match objects one at a time rather than building a list.
- In the loop `for match in re.finditer(r"\d+", text):`, each turn of the loop (1) finds the next match, (2) creates a Match object, (3) names it `match`, and (4) runs the body. When there are no more matches, the loop ends.
- `match.group()` gives the text that matched, and `match.start()` the index where it begins. In this string the indexes are:

| Character | a | b | c | | 1 | 2 | 3 | | d | e | f | | 4 | 5 | 6 |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| Index | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 |

So 123 starts at index 4 and 456 starts at index 12. Spaces are counted too.

| Feature | `re.findall()` | `re.finditer()` |
|---|---|---|
| Return type | A list | An iterator of Match objects |
| Matched text | Yes | Yes, through `match.group()` |
| Position information | No | Yes |
| Memory use | Higher | Lower |
| Best when | You need only the values | You need details about each match |

[Back to the Table of Contents](#toc)

## <a name="13-15-a-script-using-the-instance-methods-of-a-pattern-objec"></a>13.15 A script using the instance methods of a Pattern object

### <a name="example-9-the-same-eight-operations-as-pattern-methods"></a>Example 9: The same eight operations, as Pattern methods

**What the code does.** It compiles three patterns once (`p_digits`, `p_start`, `p_full`) and then calls the eight methods on them.

**How it works.** The results are exactly the same as in Example 8. Only the route differs: the pattern is compiled first, and the methods are called on the compiled object.

**Learning points**

1. `p_digits.split(text)` gives `['abc ', ' def ', '']`. The digits are removed, the spaces are kept, and the final empty string appears because the string ends right after the last match.
2. `p_digits.finditer(text)` gives spans `(4, 7)` and `(12, 15)`.
3. Compile once, use many times. This is the efficient way when the same pattern is used repeatedly.

In [10]:
import re

# Sample text used throughout the script
text = "abc 123 def 456"

# Create 3 Pattern objects (compile once, reuse later)
p_digits = re.compile(r"\d+")   # One or more digits
p_start  = re.compile(r"abc")   # Match at start
p_full   = re.compile(r"abc 123 def 456")

# 1. match(). Checks ONLY at the beginning of the string
result = p_start.match(text)
print("1. match() ->", result)
# OUTPUT: <re.Match object; span=(0, 3), match='abc'>

# 2. fullmatch(). Entire string must match the pattern
# If entire string matches, returns a Match object; otherwise, returns None.
result = p_full.fullmatch(text)
print("2. fullmatch() ->", result)
# OUTPUT: <re.Match object; span=(0, 15), match='abc 123 def 456'>

# 3. search(). Searches for pattern anywhere in the string
# If pattern is found, returns a Match object; otherwise, returns None.
result = p_digits.search(text)
print("3. search() ->", result)
# OUTPUT: <re.Match object; span=(4, 7), match='123'>

# 4. findall(). Returns ALL matches as a list

result = p_digits.findall(text)
print("4. findall() ->", result)
# OUTPUT: # ['123', '456']

# 5. finditer(). Returns an iterator yielding Match objects for all matches
print("5. finditer() ->")
for m in p_digits.finditer(text):  # Return Match objects one by one
    print(m.group(), "found at", m.span())
# OUTPUT:
# 123 found at (4, 7)
# 456 found at (12, 15)

# 6. split(). The pattern \d+ matches digit sequences and split() breaks the
# string wherever these digits occur. The matched digits are removed from the
# result, while non-matching text (including spaces) is preserved. The final
# empty string appears because splitting also occurs after the last match ("456")
result = p_digits.split(text)
print("6. split() ->", result)
# OUTPUT: ['abc ', ' def ', '']  # Note that a final empty string appears

# 7. sub(). Replaces matches with new text
result = p_digits.sub("$", text)
print("7. sub() ->", result)
# OUTPUT: abc $ def $

# 8. subn(). # Same as sub(), but also returns replacement count
result = p_digits.subn("$", text)
print("8. subn() ->", result)
# OUTPUT: ('abc $ def $', 2)  # Count of replacements is 2



1. match() -> <re.Match object; span=(0, 3), match='abc'>
2. fullmatch() -> <re.Match object; span=(0, 15), match='abc 123 def 456'>
3. search() -> <re.Match object; span=(4, 7), match='123'>
4. findall() -> ['123', '456']
5. finditer() ->
123 found at (4, 7)
456 found at (12, 15)
6. split() -> ['abc ', ' def ', '']
7. sub() -> abc $ def $
8. subn() -> ('abc $ def $', 2)


[Back to the Table of Contents](#toc)

### <a name="13-15-1-the-match-and-search-methods"></a>13.15.1 The match() and search() methods

Both return a **Match object** when they succeed, and **None** when they fail. `match()` looks only at the start of the string; `search()` looks anywhere.

Because failure gives `None`, you must check before using the result. `None` has no `group()` method, so calling it raises an `AttributeError`.

[Back to the Table of Contents](#toc)

### <a name="example-10-guarding-against-none"></a>Example 10: Guarding against None

**What the code does.** It runs `re.match(r"(\d+)", "abc 123 def 456")`, which fails because the string does not start with digits. It then shows two safe ways of dealing with the `None` that comes back: an `if` statement, and a `try ... except`.

**Learning points**

1. Method 1, the `if`, is the usual way: test with `if m is None:` or, more often, `if m:`.
2. Method 2 catches the `AttributeError` that `None.group(1)` raises. The message is `'NoneType' object has no attribute 'group'`.
3. Never call `.group()` on the result of `match()` or `search()` without checking first.

In [11]:
import re
m_match = re.match(r"(\d+)", "abc 123 def 456")
# m_match will be None since there's no match at the start of the string

# Method 1. Using an if-statement to check for None
if m_match is None:
    print("No match found for re.match.")  # This will be executed
else:
    print(m_match.group(1))  # This won't be executed

# Method 2. Using try-except to handle potential AttributeError
try:
    print(m_match.group(1))  # Access group even though m_match is None
except AttributeError as e:
    print("Caught an AttributeError:", e)  # Handle m_match is None
    print(type(e))  # Here it will print <class 'AttributeError'>



No match found for re.match.
Caught an AttributeError: 'NoneType' object has no attribute 'group'
<class 'AttributeError'>


[Back to the Table of Contents](#toc)

## <a name="13-16-the-attributes-of-a-pattern-object"></a>13.16 The attributes of a Pattern object

The **methods** of a Pattern object do the work of matching. Its **attributes** describe the compiled regex itself. There are four:

| No. | Attribute | What it stores | Type | Example value | Use it to |
|---|---|---|---|---|---|
| 1 | `pattern` | The original regex text | `str` | `'\d+'` | See or display the regex the object was built from |
| 2 | `groups` | The number of capturing groups | `int` | `2` | Check how many groups you can ask for |
| 3 | `groupindex` | Named group to group number | `dict` | `{'word': 1}` | Work with named groups |
| 4 | `flags` | The compilation flags | `int` | `34` | Check how matching will behave |

Note that `groups` counts only **capturing** groups; non-capturing ones `(?: ... )` are not counted. An empty `groupindex` simply means there are no named groups.

[Back to the Table of Contents](#toc)

### <a name="example-11-the-four-attributes-at-a-glance"></a>Example 11: The four attributes at a glance

**What the code does.** It compiles `r"(?P<word>\w+)-(\d+)"` and prints all four attributes.

**How it works.** The pattern has two capturing groups. The first is **named** `word` with the syntax `(?P<name> ... )`; the second is an ordinary numbered group.

**Learning points**

1. `pattern.groups` is 2, and `pattern.groupindex` is `{'word': 1}`: the name `word` refers to group 1.
2. `pattern.flags` prints 32. That is `re.UNICODE`, which Python 3 switches on by default for string patterns.
3. The attributes are read without brackets. They are values, not methods.

In [12]:
import re
pattern = re.compile(r"(?P<word>\w+)-(\d+)")
print(pattern.pattern)  # (?P<word>\w+)-(\d+)
print(pattern.groups)   # 2
print(pattern.groupindex)  # {'word': 1}
print(pattern.flags)    # 32


(?P<word>\w+)-(\d+)
2
{'word': 1}
32


[Back to the Table of Contents](#toc)

### <a name="example-12-the-same-four-attributes-one-at-a-time"></a>Example 12: The same four attributes, one at a time

**What the code does.** It repeats the four attributes, each with its own small pattern, so that you can see what changes.

**Learning points**

1. `re.compile(r"\d+").pattern` gives back the text `\d+`.
2. `re.compile(r"(\d+)-(\w+)").groups` is 2.
3. The last pattern is compiled with the flag `re.I`, so `flags` prints 34, which is 32 (`re.UNICODE`) plus 2 (`re.IGNORECASE`).

In [13]:
# 1. pattern. Returns original regex text from which Pattern object was created.
import re
pattern = re.compile(r"\d+")

print(pattern.pattern)  # \d+. Gets the original regex source.

# 2. groups. Returns the total number of capturing groups.
pattern = re.compile(r"(\d+)-(\w+)")

print(pattern.groups)  # 2. because there are two capturing groups.

# 3. groupindex. Returns a dictionary mapping group name → group number.
pattern = re.compile(r"(?P<word>\w+)-(\d+)")
print(pattern.groupindex)  # {'word': 1}. Meaning: word → group 1

# 4. flags. Returns the regex compilation flags.
pattern = re.compile(r"abc", re.I)
print(pattern.flags)  # 34. Includes re.IGNORECASE internally.


\d+
2
{'word': 1}
34


[Back to the Table of Contents](#toc)

### <a name="13-16-1-using-flags-to-change-how-matching-works"></a>13.16.1 Using flags to change how matching works

The full signature of the factory function is:

```python
re.compile(pattern, flags=0)
```

Since the parameter `flags` has a default value of 0, you may leave it out. When you do pass a flag, you change how the regex engine behaves.

**Why `re.I` and not just `I`?** When you write `import re`, you bring the whole module into your program. To take something out of it you use dot notation: `re` is the module and `I` is a constant inside it. If you wrote `I` alone, Python would look for a variable of your own with that name and raise a `NameError`.

| No. | Flag | Value | What it changes | When to use it | Example |
|---|---|---|---|---|---|
| 1 | `re.I` or `re.IGNORECASE` | 2 | Matching ignores the case of letters | Upper and lower case should be treated the same | `"cat"` matches `"CAT"` |
| 2 | `re.M` or `re.MULTILINE` | 8 | `^` and `$` match at the start and end of **each line** | Multi-line text | `^cat` matches "cat" at the start of any line |
| 3 | `re.S` or `re.DOTALL` | 16 | The dot also matches a newline | The text contains line breaks | `.` matches `\n` |
| 4 | `re.U` or `re.UNICODE` | 32 | Unicode-aware matching | On by default in Python 3 | `\w` matches accented letters |

The flag values are powers of 2, so they can be combined with the bitwise OR operator `|`. Each flag is one "bit" in an integer:

- `re.I` is 2, which is binary 00010
- `re.M` is 8, which is binary 01000
- `re.I | re.M` is 10, which is binary 01010

The compiled object stores the result in `p.flags`, and `re.compile()` reads that number to know which features you asked for. Because no two combinations give the same number, the engine can always tell them apart.

[Back to the Table of Contents](#toc)

### <a name="try-it-three-flags-in-action"></a>Try it: three flags in action

This cell is not in the book. These three examples appear in the text; here they are, ready to run.

In [14]:
import re

print(re.search("cat", "CAT", re.I))          # ignore case
print(re.search("^cat", "dog\ncat", re.M))    # ^ matches the start of each line
print(re.search("a.b", "a\nb", re.S))         # the dot also matches a newline

print("Without the flag:", re.search("cat", "CAT"))   # None

<re.Match object; span=(0, 3), match='CAT'>
<re.Match object; span=(4, 7), match='cat'>
<re.Match object; span=(0, 3), match='a\nb'>
Without the flag: None


[Back to the Table of Contents](#toc)

### <a name="try-it-reading-the-flags-of-a-compiled-pattern"></a>Try it: reading the flags of a compiled pattern

This cell is not in the book. It combines two flags and then checks whether a particular flag is set, using the bitwise AND operator `&`.

In [15]:
import re

p = re.compile(r"hello", re.I | re.M)   # compile with IGNORECASE and MULTILINE
print(p.flags)   # 42: re.UNICODE (32) + re.I (2) + re.M (8)

if p.flags & re.I:                      # is the IGNORECASE flag set?
    print("Case Insensitive is ON")

if p.flags & re.S:                      # is the DOTALL flag set?
    print("DotAll is ON")
else:
    print("DotAll is OFF")

42
Case Insensitive is ON
DotAll is OFF


[Back to the Table of Contents](#toc)

## <a name="13-17-the-methods-of-a-match-object"></a>13.17 The methods of a Match object

When a match succeeds, Python creates a Match object that holds the result. Its methods fall into four groups: (1) core methods, (2) position and span methods, (3) string and context attributes, and (4) its boolean behaviour.

[Back to the Table of Contents](#toc)

### <a name="13-17-1-the-core-methods"></a>13.17.1 The core methods

| No. | Method | What it does | Returns | Note |
|---|---|---|---|---|
| 1 | `m.group()` or `m.group(0)` | The text matched by the whole pattern | `str` | The two are the same |
| 2 | `m.group(n)` | The text matched by group n | `str` | An error if group n does not exist |
| 3 | `m.groups()` | All the capturing groups | `tuple` | An empty tuple if there are none |
| 4 | `m.groupdict()` | The named groups | `dict` | An empty dict if there are none |

If you ask for a group that does not exist, Python raises `IndexError: no such group`. So either check first or wrap the call in `try ... except`.

[Back to the Table of Contents](#toc)

### <a name="example-13-the-core-methods-of-a-match-object"></a>Example 13: The core methods of a Match object

**What the code does.** It searches for `(\d+)` in `"abc 123 def 456"` and prints `group(0)`, `group(1)`, `groups()` and, using a second pattern with a named group, `groupdict()`.

**Learning points**

1. `group(0)` and `group(1)` both give `123` here, but for different reasons: group 0 is the whole match, and group 1 is the text captured by the brackets, which happens to be the same.
2. `groups()` gives a **tuple**: `('123',)`. The comma shows that it is a tuple with one item.
3. `(?P<digits>\d+)` names the group, so `groupdict()` gives `{'digits': '123'}`.
4. `search()` stops at the first match, which is why 456 never appears.

In [16]:
import re
m = re.search(r"(\d+)", "abc 123 def 456")  # Search for one or more digits

# 1. m.group() or m.group(0) - Entire match.
print(f"m.group(0) -> {m.group(0)}")  # Entire match
# Output: m.group(0) -> 123

# 2. m.group(1) - First capturing group
print(f"m.group(1) -> {m.group(1)}")  #
# Output: m.group(1) -> 123

# 3. m.groups() - All capturing groups as a tuple. Note the plural 'groups'
print(f"m.groups() -> {m.groups()}")
# Output: m.groups() -> ('123',)

# 4. m.groupdict() - Named capturing groups as a dictionary
m_named = re.search(r"(?P<digits>\d+)", "abc 123 def 456")  # Search with named capturing group
print(f"m_named.groupdict() -> {m_named.groupdict()}")
# Output: m_named.groupdict() -> {'digits': '123'}



m.group(0) -> 123
m.group(1) -> 123
m.groups() -> ('123',)
m_named.groupdict() -> {'digits': '123'}


[Back to the Table of Contents](#toc)

### <a name="13-17-2-more-about-group"></a>13.17.2 More about group()

| Form | What it returns |
|---|---|
| `group()` or `group(0)` | The entire matched substring, as a string |
| `group(n)` | The text of the nth group, as a string. Group 1 is the first pair of brackets, **not** the whole match |
| `group(m, n, k, ...)` | A tuple with those groups, in the order you asked for them |

[Back to the Table of Contents](#toc)

### <a name="13-17-3-named-groups-and-groupdict"></a>13.17.3 Named groups and groupdict()

Numbered groups get confusing in long patterns. A **named group**, written `(?P<name> ... )`, gives a group a label, like a variable name. `m.groupdict()` then returns a dictionary whose keys are those labels.

For example, in `re.search(r"(?P<digits>\d+)", "abc 123 def 456")`:

| Part | Meaning |
|---|---|
| `( ... )` | A capturing group: the part of the string we want |
| `?P<digits>` | Names that group `digits`, so the name becomes a dictionary key |
| `\d+` | The rule itself: one or more digits |

A named group is still numbered as well, so both `m.group(1)` and `m.group('digits')` work. Names matter in long patterns: if you add a new group at the front, the numbers all shift, but the names stay put.

[Back to the Table of Contents](#toc)

### <a name="try-it-reaching-a-group-by-number-and-by-name"></a>Try it: reaching a group by number and by name

This cell is not in the book.

In [17]:
import re

m_named = re.search(r"(?P<digits>\d+)", "abc 123 def 456")
print(m_named.group(1))          # by number
print(m_named.group('digits'))   # by name
print(m_named.groupdict())

123
123
{'digits': '123'}


[Back to the Table of Contents](#toc)

### <a name="example-14-group-with-several-arguments"></a>Example 14: group() with several arguments

**What the code does.** It matches `(abc)(123)` against `"abc123"`, which gives two groups, and then asks for them in several ways.

**Learning points**

1. `group()` and `group(0)` both give `abc123`, the entire match.
2. `group(1, 2)` gives the tuple `('abc', '123')`, and `group(1, 2, 0)` gives `('abc', '123', 'abc123')`. The order of the arguments decides the order in the tuple.
3. The last line is commented out on purpose. `group(3)` would raise `IndexError: no such group`, because the pattern has only two groups.

In [18]:
import re
match = re.match(r"(abc)(123)", "abc123")
print(match.group())    # "abc123" matches the entire match
print(match.group(0))   # "abc123" also matches the entire match
print(match.group(1))   # "abc" matches the first capturing group
print(match.group(2))   # "123" matches the second capturing group
print(match.group(1, 2))  # ("abc", "123") matches both groups as a tuple
print(match.group(1, 2, 0))  # ("abc", "123", "abc123") matches groups 1, 2, and the entire match as a tuple

# Following if uncommented raises IndexError as there is no group 3
# print(match.group(3))  # ERROR


abc123
abc123
abc
123
('abc', '123')
('abc', '123', 'abc123')


[Back to the Table of Contents](#toc)

### <a name="13-17-4-position-and-span-methods"></a>13.17.4 Position and span methods

| Method | Mode | What it refers to | Returns | Note |
|---|---|---|---|---|
| `start()` | Whole match | Start index | `int` | Counting starts at 0 |
| `end()` | Whole match | End index | `int` | The end index itself is not included |
| `span()` | Whole match | `(start, end)` | `tuple` | A shortcut for both at once |
| `start(n)` | Group n | Start index of that group | `int` | Error if the group is missing |
| `end(n)` | Group n | End index of that group | `int` | |
| `span(n)` | Group n | `(start, end)` of that group | `tuple` | |

These are not six different methods but three, each usable in two modes: without an argument they refer to the whole match, and with a group number they refer to that group.

[Back to the Table of Contents](#toc)

## <a name="13-18-the-attributes-of-a-match-object"></a>13.18 The attributes of a Match object

| No. | Attribute | Type | What it is | Why it is useful |
|---|---|---|---|---|
| 1 | `m.string` | `str` | The exact string you passed to `search()` or `match()` | A handy way to reach the source text. It is read-only |
| 2 | `m.re` | Pattern | The Pattern object that produced this match | If a function receives a Match object but does not know the regex, `m.re.pattern` tells it |
| 3 | `m.pos` | `int` | The index where the engine started looking | Usually 0, but not if you passed a start index, as in `pattern.search(text, 5)` |
| 4 | `m.endpos` | `int` | The index where the engine stopped looking | Usually the length of the string |

[Back to the Table of Contents](#toc)

### <a name="13-18-1-match-objects-are-true"></a>13.18.1 Match objects are true

A Match object always counts as `True` in a boolean test:

- A Match object exists only when the match succeeded, so `bool(m)` is `True`.
- When nothing matched, the result is `None`, and `bool(None)` is `False`.
- So you can write `if m:` directly.
- Always check the result of `match()` or `search()` before using it.

[Back to the Table of Contents](#toc)

## <a name="13-19-the-attributes-of-a-pattern-object-and-a-match-object-"></a>13.19 The attributes of a Pattern object and a Match object compared

| Aspect | Pattern attributes | Match attributes |
|---|---|---|
| Belong to | The Pattern object | The Match object |
| Created when | The pattern is compiled | A match is found |
| Exist without a match? | Yes | No |
| Purpose | Information about the regex itself | Information about one particular result |
| Reusability | Reusable across many strings | Tied to one string and one match |
| Lifetime | As long as the pattern exists | Short: only for that result |
| Object type | `re.Pattern` | `re.Match` |

[Back to the Table of Contents](#toc)

## <a name="13-20-greedy-and-non-greedy-quantifiers"></a>13.20 Greedy and non-greedy quantifiers

Quantifiers come in two flavours:

- A **greedy** quantifier tries to match as many repetitions as possible. `*`, `+`, `?` and `{m,n}` are greedy by default.
- A **non-greedy** (or lazy) quantifier tries to match as few as possible. You make a quantifier lazy by adding `?` after it: `*?`, `+?`, `??`, `{m,n}?`.

So the question mark has two jobs. On its own it means "zero or one". After another quantifier it changes greedy behaviour into lazy behaviour.

![Greedy and lazy quantifiers on the same HTML string](https://raw.githubusercontent.com/ag999git/001-Python-book-2026/main/resources/ch-13-nb-07-greedy-lazy.png)

[Back to the Table of Contents](#toc)

### <a name="example-15-greedy-and-lazy-on-two-examples"></a>Example 15: Greedy and lazy, on two examples

**What the code does.** The first part matches `.*\d+` and `.*?\d+` against `"abc123xyz456"`. The second part matches `<.*>` and `<.*?>` against a short piece of HTML.

**How it works.**

| Pattern | Result | Why |
|---|---|---|
| `.*\d+` | `abc123xyz456` | `.*` takes everything, then gives back just enough for `\d+` to match one digit |
| `.*?\d+` | `abc123` | `.*?` takes as little as possible, so matching stops at the first run of digits |
| `<.*>` | The whole 45-character string | The greedy `.*` runs to the last `>` |
| `<.*?>` | `<!DOCTYPE html>` | The lazy `.*?` stops at the first `>` |

**Learning points**

1. Both quantifiers find a valid match. They differ in **how much** they take.
2. For HTML-like text, the lazy form is almost always what you want; the greedy form swallows everything between the first and the last bracket.
3. In this script the patterns are written with `"\\d+"` and plain quotes rather than raw strings. Both work, but a raw string such as `r"\d+"` is easier to read.

In [19]:
import re
text = "abc123xyz456"
# 1. Greedy matching
m1 = re.search(".*\\d+", text) # greedy
print(m1.group())  # Output: abc123xyz456

# 2. Non-greedy (lazy) matching by adding ? after the quantifier *
# ".*?\\d+" is non greedy because .*? matches as little text as possible
m2 = re.search(".*?\\d+", text) # non-greedy
print(m2.group())  # Output: abc123

# Given below is another example. In the given string namely str_html, the first closing angular bracket  > appears at the end of <!DOCTYPE html>. So non-greedy (lazy) will stop here.
# On the other hand, the last angular bracket > appears at </html>, so greedy will go up to that last angular bracket.

import re
str_html = '<!DOCTYPE html> <html> <head> </head> </html>'
print('length string->', len(str_html))  # length of the string-> 45

# 1.GREEDY.Does not have ? after *. This makes it greedy (default)
pat_greedy = '<.*>' #
print('length greedy->', re.match(pat_greedy, str_html).span())
# Output: length greedy-> (0, 45)
print('groups greedy->', re.match(pat_greedy, str_html).group())
# Output: <!DOCTYPE html> <html> <head> </head> </html>

# 2. NON-GREEDY. It has ? after * which makes it non-greedy (lazy)
pat_nongreedy = '<.*?>' #
print('length non-greedy->', re.match(pat_nongreedy, str_html).span())
# Output: length non-greedy-> (0, 15)
print('groups non-greedy->', re.match(pat_nongreedy, str_html).group())
# Output: <!DOCTYPE html>


abc123xyz456
abc123
length string-> 45
length greedy-> (0, 45)
groups greedy-> <!DOCTYPE html> <html> <head> </head> </html>
length non-greedy-> (0, 15)
groups non-greedy-> <!DOCTYPE html>


[Back to the Table of Contents](#toc)

## <a name="part-c-advanced-topics"></a>Part C: Advanced topics

This part covers capturing and non-capturing groups, backreferences and lookarounds. They are not needed for a basic understanding of regular expressions, and a beginner may skip them.

[Back to the Table of Contents](#toc)

## <a name="13-21-the-regex-parenthesis-family"></a>13.21 The regex parenthesis family

Round brackets do several different jobs in a regex. The four main ones are:

| No. | Kind | Syntax | What it does |
|---|---|---|---|
| 1 | Capturing group | `( ... )` | Groups **and** stores the matched text |
| 2 | Non-capturing group | `(?: ... )` | Groups only; stores nothing |
| 3 | Lookarounds | `(?= )`, `(?! )`, `(?<= )`, `(?<! )` | Zero-width checks before or after the current position |
| 4 | Inline flags | `(?i)`, `(?m)`, `(?s)` | Change the behaviour of the engine inside the pattern |

[Back to the Table of Contents](#toc)

## <a name="13-22-capturing-and-non-capturing-groups"></a>13.22 Capturing and non-capturing groups

Brackets are used for two things: **grouping** parts of a pattern, and **capturing** the text for later use.

- A normal group `( ... )` does both.
- A non-capturing group `(?: ... )` groups only. It does not store the text.

**1. Capturing group.** The syntax is `(pattern)`. It (1) stores the matched text, (2) creates a group number, and (3) supports backreferences such as `\1`.

**2. Non-capturing group.** The syntax is `(?:pattern)`. It (1) groups parts of the regex, (2) does not store the text, and (3) does not create a group number.

Note the difference in syntax: a capturing group has nothing after the opening bracket, while a non-capturing group has `?:` right after it.

**Why use non-capturing groups?** When (1) grouping is needed but (2) the captured text is not. They (1) keep the group numbering simple, (2) make the regex easier to read, and (3) avoid storing text you will never use.

| Feature | Capturing `( )` | Non-capturing `(?: )` |
|---|---|---|
| Stores the matched text | Yes | No |
| Creates a group number | Yes | No |
| Supports backreferences | Yes | No |
| Used for extraction | Yes | Usually no |
| Used for grouping | Yes | Yes |
| Keeps numbering clean | No | Yes |

[Back to the Table of Contents](#toc)

### <a name="try-it-the-same-pattern-with-and-without-capturing"></a>Try it: the same pattern, with and without capturing

This cell is not in the book. It is the small pair of examples from the text.

In [20]:
import re

m = re.search(r"(cat)", "black cat")       # capturing
print(m.group(1))                          # cat
print(m.groups())                          # ('cat',)

m = re.search(r"(?:cat)", "black cat")     # non-capturing
print(m.group(0))                          # cat: the match itself is the same
print(m.groups())                          # (): nothing was stored

cat
('cat',)
cat
()


[Back to the Table of Contents](#toc)

### <a name="example-16-four-uses-of-non-capturing-groups"></a>Example 16: Four uses of non-capturing groups

**What the code does.** It shows four situations where grouping is needed but capturing is not:

| No. | Purpose | Pattern | Result |
|---|---|---|---|
| 1 | Repetition | `(?:ab)+` on `"ababab"` | `['ababab']` |
| 2 | Alternation | `(?:cat\|dog\|rat)` on `"cat dog rat bat"` | `['cat', 'dog', 'rat']` |
| 3 | Cleaner numbering | `(?:Mr\|Ms\|Dr)\. (\w+)` on `"Dr. John"` | `John` is group 1 |
| 4 | Removing repeated words | `(\b\w+)(?:\s+\1)+` on `"The The cat cat sat sat"` | `The cat sat` |

**How it works.**

- In example 1 the `+` has to apply to the whole `ab` sequence, so brackets are needed; but the text itself is not wanted, so `(?: )` is used.
- In example 2 the brackets only hold the alternatives together.
- In example 3 the title has to be part of the pattern, but only the name is wanted. Because the title is in a non-capturing group, the name becomes group 1 rather than group 2.
- In example 4, `(\b\w+)` captures a word as group 1, and `(?:\s+\1)+` matches one or more repetitions of that same word. `\1` is a **backreference**: it stands for whatever group 1 matched. `re.sub()` then replaces the whole run with one copy.

**Learning points**

1. `findall()` behaves differently when the pattern has capturing groups: it returns the groups instead of the whole match. Non-capturing groups avoid that surprise, which is why example 1 gives `['ababab']` rather than `['ab']`.
2. A non-capturing group cannot be used with a backreference, because nothing is stored.

In [21]:
import re
# 1.    Example 1: Grouping for Repetition
text = "ababab"
# (?:ab)+ is non-capturing group (?:...) it doesnt create numbered group for
# the match, but allows application of + quantifier to the whole "ab" sequence
result = re.findall(r"(?:ab)+", text)
print(result)  # Output: ['ababab']

# 2.    Example 2: Grouping for Alternation
text = "cat dog rat bat"
# (?:cat|dog|rat) is non capturing group (?:...) so doesn't create numbered
# group for the match. The | operator matches any of cat, dog, or rat.
result = re.findall(r"(?:cat|dog|rat)", text)
print(result)  # Output: ['cat', 'dog', 'rat']
# Explanation: The group is used only to combine alternatives.

# 3.    Example 3: Cleaner Group Numbering
# Explaining: (?:Mr|Ms|Dr)\. (\w+)
# (?:Mr|Ms|Dr)→ non-capturing group→ matches title but doesnt create numbered group
# while (\w+) captures the name as Group 1.
m = re.search(r"(?:Mr|Ms|Dr)\. (\w+)", "Dr. John")
print(m.group(1))  # Output: John

# 4.    Example 4: Removing Duplicate Words
text = "The The cat cat sat sat"
# (\b\w+)(?:\s+\1)+ → (\b\w+) captures a word as Group 1, and (?:\s+\1)+ matches
# one or more occurrences of same word preceded by whitespace, but doesnt capture
# them as a group. The re.sub() function replaces the entire matched sequence
# with just the first occurrence of the word (Group 1)→ removing duplicates
pattern = r"(\b\w+)(?:\s+\1)+"
result = re.sub(pattern, r"\1", text)
print(result)  # Output: The cat sat


['ababab']
['cat', 'dog', 'rat']
John
The cat sat


[Back to the Table of Contents](#toc)

## <a name="13-23-backreferences"></a>13.23 Backreferences

A **backreference** lets you match, or reuse, the same text that a capturing group matched earlier. Inside a pattern, `\1` means "whatever group 1 matched", `\2` means group 2, and so on. In a replacement string you use the same numbers to put the captured text back.

So brackets serve two purposes: they create sub-expressions, and they create backreferences.

[Back to the Table of Contents](#toc)

### <a name="13-23-1-using-a-backreference-to-swap-two-words"></a>13.23.1 Using a backreference to swap two words

Consider the pattern:

```python
r'([^\s]+)\s+([^\s]+)'
```

| Part | Meaning |
|---|---|
| `([^\s]+)` | Group 1. `[^\s]` is "any character that is not whitespace", and `+` means one or more. So this is a word |
| `\s+` | One or more spaces, tabs or newlines |
| `([^\s]+)` | Group 2: the second word |

With `re.sub()` and the replacement `r'\2 \1'`, "cat dog" becomes "dog cat".

[Back to the Table of Contents](#toc)

### <a name="try-it-swapping-two-adjacent-words"></a>Try it: swapping two adjacent words

This cell is not in the book. It uses the pattern from the text above.

In [22]:
import re

pattern = r'([^\s]+)\s+([^\s]+)'
print(re.sub(pattern, r'\2 \1', "cat dog"))
print(re.sub(pattern, r'\2 \1', "hello world python rocks"))

dog cat
world hello rocks python


[Back to the Table of Contents](#toc)

### <a name="example-17-reordering-lastname-firstname"></a>Example 17: Reordering "LastName, FirstName"

**What the code does.** It takes the text `"Doe, John; Smith, Alice"` and turns it into `"John, Doe; Alice, Smith"`, using two capturing groups and a replacement that puts them back in the other order.

**How it works.**

| Part of the pattern | Meaning |
|---|---|
| `([A-Za-z]+)` | Group 1: the last name, letters only |
| `,\s+` | A comma and one or more spaces. This part is matched but not captured |
| `([A-Za-z]+)` | Group 2: the first name |

In the replacement `r'\2, \1'`, `\2` is the first name and `\1` the last name, so the two are swapped.

**Learning points**

1. The comma has to be part of the pattern, otherwise `([A-Za-z]+)\s+([A-Za-z]+)` never matches this text, because a comma sits between the two names.
2. Navigation text such as `,\s+` is deliberately left **outside** the brackets. It is matched and thrown away.
3. In the replacement string, `\1` and `\2` are written in a raw string, `r'\2, \1'`.

In [23]:
import re  # Import the regular expression module

# Pattern explanation:
# ([A-Za-z]+)  → Group 1: First name (only letters)
# ,\s+         → A comma and one or more spaces
# ([A-Za-z]+)  → Group 2: Last name
name_pattern = r'([A-Za-z]+),\s+([A-Za-z]+)'

# Sample text containing multiple names
text = "Doe, John; Smith, Alice"

# Replace using backreferences:
# \2 → Last name
# \1 → First name
# Output format: LastName, FirstName
result = re.sub(name_pattern, r'\2, \1', text)

# Display the result
print(result)
# Output: John, Doe; Alice, Smith


John, Doe; Alice, Smith


[Back to the Table of Contents](#toc)

## <a name="13-24-the-role-of-parentheses"></a>13.24 The role of parentheses

Parentheses do two major jobs:

| Purpose | Description | Example |
|---|---|---|
| **Grouping** | Treat several characters as one unit, so that a quantifier applies to all of them | `(xyz)*` |
| **Capturing** | Save the matched text so that it can be reused later | `(\w+)` |

**Grouping.** `(xyz)*` matches an empty string, `xyz`, `xyzxyz`, `xyzxyzxyz` and so on. Without the brackets, `xyz*` applies the `*` only to the `z`, so it matches `xy`, `xyz`, `xyzz` and so on. Brackets change the scope of a quantifier.

**Capturing.** Captured text can be used again in two places: (1) inside Python with `group(1)`, `group(2)`, and (2) inside the regex itself with `\1`, `\2`. For example, `(\b\w+)\s+\1` finds a word repeated twice.

The difference in one line: capturing stores text in memory, while a backreference reuses text that was stored. `(\w+)` only captures; `(\w+)\s+\1` captures **and** reuses.

[Back to the Table of Contents](#toc)

## <a name="13-25-removing-consecutive-duplicate-words"></a>13.25 Removing consecutive duplicate words

### <a name="example-18-cleaning-repeated-words-out-of-a-sentence"></a>Example 18: Cleaning repeated words out of a sentence

**What the code does.** It takes `"cat cat cat dog dog fish fish fish fish bird"` and reduces every run of repeated words to a single word.

**How it works.** The pattern is `r'(\b\w+)(?:\s+\1)+'`:

| Part | Meaning |
|---|---|
| `(\b\w+)` | Group 1: a complete word. `\b` is a word boundary and `\w+` is one or more word characters |
| `(?: ... )` | A non-capturing group: used only to hold the next two pieces together |
| `\s+` | One or more spaces |
| `\1` | The same word again |
| `+` | One or more repetitions of "space plus the same word" |

`re.sub(pattern, r'\1', text)` replaces the whole run with the single captured word.

**Learning points**

1. This cell prints `Cleaned text:->  cat dog fish bird`.
2. The pattern only removes **consecutive** duplicates. "cat dog cat" is left alone.
3. `\b` stops the pattern from matching inside longer words.

In [24]:
import re
# Import Python's regular expression module

# Sample text with consecutive duplicate words
text = "cat cat cat dog dog fish fish fish fish bird"

# Regex pattern to match consecutive duplicate words
pattern = r'(\b\w+)(?:\s+\1)+'
# Pattern explanation:
# (\b\w+)      → Captures a complete word and stores it as Group 1
#     \b       → Word boundary (ensures full word match)
#     \w+      → One or more word characters (letters, digits, underscore)
# (?: )        → Non-capturing group (used only for grouping, not storing)
#     \s+      → One or more whitespace characters
#     \1       → Backreference to the word captured in Group 1
#     +        → Matches one or more repetitions of the same word
#
# Overall meaning:
# "Match a word followed by one or more repetitions of the same word"

# Replace duplicate word sequences with a single occurrence
cleaned_text = re.sub(pattern, r'\1', text)
# re.sub() searches for the pattern and replaces it
# r'\1' means we keep only the first captured word
# All repeated copies are removed

print("Cleaned text:-> ", cleaned_text)
# Output: Cleaned text:->  cat dog fish bird


Cleaned text:->  cat dog fish bird


[Back to the Table of Contents](#toc)

## <a name="13-26-lookarounds"></a>13.26 Lookarounds

A **lookaround** peeks at the text without moving across it. Think of it as a condition check rather than a way of grabbing text.

**Why "zero-width"?** In ordinary matching, every matched character makes the cursor step forward; that is consumption. In a lookaround the cursor never takes that step. So a lookaround can check twenty characters and still have a span of zero.

There are four lookarounds:

| | Syntax | Name | Meaning | Direction | The question |
|---|---|---|---|---|---|
| Lookahead | `(?=pattern)` | Positive lookahead | The text **after** the position matches | Forward | "Is this followed by ...?" |
| | `(?!pattern)` | Negative lookahead | The text after the position does **not** match | Forward | "Is this not followed by ...?" |
| Lookbehind | `(?<=pattern)` | Positive lookbehind | The text **before** the position matches | Backward | "Is this preceded by ...?" |
| | `(?<!pattern)` | Negative lookbehind | The text before the position does **not** match | Backward | "Is this not preceded by ...?" |

![The four lookarounds: two lookaheads and two lookbehinds](https://raw.githubusercontent.com/ag999git/001-Python-book-2026/main/resources/ch-13-nb-08-lookaround.png)

**When are lookarounds essential?** Ordinary regex works well when order matters and you want to consume the characters as you match. Lookarounds are needed when:

- the order does not matter, but several conditions must all hold (password rules);
- you must match something only because of its context, without eating that context;
- you need overlapping matches (the "banana" problem).

In short, lookarounds turn a regex from a pattern matcher into a rule checker.

[Back to the Table of Contents](#toc)

### <a name="13-26-1-using-a-lookaround-to-validate-a-password"></a>13.26.1 Using a lookaround to validate a password

The rules: (1) at least 8 characters, (2) at least one uppercase letter, (3) at least one lowercase letter.

[Back to the Table of Contents](#toc)

### <a name="example-19-password-validation-with-lookaheads"></a>Example 19: Password validation with lookaheads

**What the code does.** It compiles `r"^(?=.*[A-Z])(?=.*[a-z]).{8,}$"` and tests five passwords.

**How it works.**

| Part | Meaning |
|---|---|
| `^` | Start of the string |
| `(?=.*[A-Z])` | Look ahead: somewhere after this position there is an uppercase letter. The cursor does not move |
| `(?=.*[a-z])` | Look ahead again: there is also a lowercase letter |
| `.{8,}` | Now really match at least 8 characters |
| `$` | End of the string |

The two lookaheads both start their check at position 0. Because neither consumes anything, the third condition, the length, is checked on the whole string as well. That is how three independent rules are applied to the same text.

**Learning points**

1. `no_uppercase` fails the first lookahead; `NO_LOWERCASE` fails the second; `Short` passes both but is too short.
2. `Password` and `GoodPass1` pass all three rules.
3. The order of the rules in the pattern does not matter, because the lookaheads do not consume anything.

In [25]:
import re
# Regex with lookarounds
# ^ asserts position at start of the string
# .* means any character (.) zero or more times (*)
# Password rules using lookahead assertions:
# (?=.*[A-Z]) -> Any character 0 or more times. Then 1 uppercase letter
# (?=.*[a-z]) -> Any character 0 or more times. Then 1 lowercase letter
# .{8,}       -> at least 8 characters total

password_pattern = re.compile(r"^(?=.*[A-Z])(?=.*[a-z]).{8,}$")

# Test passwords
passwords = [
    "no_uppercase",     # no uppercase
    "NO_LOWERCASE",     # no lowercase
    "Short",            # too short
    "Password",         # valid
    "GoodPass1"         # valid
]

# Test each password
for pwd in passwords:  # Check each password
    if password_pattern.search(pwd):  # Valid password
        print(pwd, "-> VALID")
    else:  # Invalid password
        print(pwd, "-> INVALID")


no_uppercase -> INVALID
NO_LOWERCASE -> INVALID
Short -> INVALID
Password -> VALID
GoodPass1 -> VALID


[Back to the Table of Contents](#toc)

### <a name="example-20-the-same-check-without-lookarounds"></a>Example 20: The same check without lookarounds

**What the code does.** It does the same validation without lookaheads, and needs two alternatives to do it: uppercase before lowercase, or lowercase before uppercase.

**How it works.** `^[A-Z].*[a-z].{6,}$` says: an uppercase letter, then anything, then a lowercase letter, then at least 6 more characters. The second condition is the mirror image. The two are joined with `|`.

**Learning points**

1. The results are the same as in Example 19, but the pattern is harder to read and to change.
2. Add a third rule, such as "must contain a digit", and the number of alternatives grows quickly. With lookaheads you would simply add `(?=.*\d)`.
3. `rf"({condition1})|({condition2})"` is an f-string **and** a raw string: the two conditions are inserted into the pattern.
4. Without lookarounds you must think about **order**. With them you only state the **conditions**.

In [26]:
import re

# REGEX WITHOUT LOOKAROUNDS
# Explanation:
# 1. Minimum length 8 → .{8,}
# 2. Must contain:
#    a) uppercase before lowercase OR
#    b) lowercase before uppercase
# This forces us to write BOTH cases using alternation (|)
# Upper case before lowercase: ^[A-Z].*[a-z].{6,}$
# Lower case before uppercase: ^[a-z].*[A-Z].{6,}$

condition1 = "^[A-Z].*[a-z].{6,}$"
condition2 = "^[a-z].*[A-Z].{6,}$"
pattern_no_lookaround = re.compile(rf"({condition1})|({condition2})")

# Passwords to test
passwords = [
    "no_uppercase",     # no uppercase
    "NO_LOWERCASE",     # no lowercase
    "Short",            # too short
    "Password",         # valid
    "GoodPass1"         # valid
]

# Test each password
for pwd in passwords:
    if pattern_no_lookaround.search(pwd):
        print(pwd, "-> VALID")
    else:
        print(pwd, "-> INVALID")

# Output:
# no_uppercase  -> INVALID
# NO_LOWERCASE  -> INVALID
# Short         -> INVALID
# Password      -> VALID
# GoodPass1     -> VALID


no_uppercase -> INVALID
NO_LOWERCASE -> INVALID
Short -> INVALID
Password -> VALID
GoodPass1 -> VALID


[Back to the Table of Contents](#toc)

### <a name="13-26-2-lookarounds-and-the-overlapping-banana-problem"></a>13.26.2 Lookarounds and the overlapping ("banana") problem

An ordinary regex consumes characters as it matches, and carries on searching only after the end of the previous match. So a character that is part of one match cannot be part of the next. That is a problem when the matches overlap.

Take `"banana"` and the pattern `ana`. There are two of them:

1. b **ana** na, starting at index 1
2. ban **ana**, starting at index 3

`re.findall(r"ana", "banana")` finds only the first: it consumes the middle `a`, so the second one cannot start.

**The solution** is a positive lookahead with a capturing group inside it: `r"(?=(ana))"`. The lookahead checks the condition without moving the cursor, and the brackets take a snapshot of what it saw.

![Finding the overlapping "ana" inside "banana" with a lookahead](https://raw.githubusercontent.com/ag999git/001-Python-book-2026/main/resources/ch-13-nb-09-banana.png)

[Back to the Table of Contents](#toc)

### <a name="example-21-finding-overlapping-matches"></a>Example 21: Finding overlapping matches

**What the code does.** It uses `re.finditer(r"(?=(ana))", "banana")` and, for every match, prints the Match object, its span, the text captured in group 1, and its starting index.

**How it works.** At each position the engine asks "is there an `ana` starting here?". At positions 1 and 3 the answer is yes. Each success creates a Match object of **zero width**, whose group 1 holds the captured `ana`.

**Learning points**

1. `m.group(0)` is empty, because the lookahead consumed nothing. The text you want is in `m.group(1)`.
2. `m.span()` is `(1, 1)` and then `(3, 3)`: a start and an end that are the same, which is what zero-width means. The span gives the position, not the text.
3. Two separate Match objects are created, each with its own position and its own group 1. They are not one combined result.

In [27]:
import re

text = "banana"
# We look for a position that is followed by 'ana'
# The lookahead (?=...) has zero width, so the cursor stays put!
pattern = r"(?=(ana))"  # Lookahead to find 'ana' without consuming characters

matches = re.finditer(pattern, text)  # Find all matches in the text
# We use re.finditer to get an iterator over all matches
# matches will find overlapping occurrences of 'ana' in 'banana'
# Each match has zero width, but captures 'ana' in group 1
for m in matches:
    # Match object for each occurrence
    print("Match object:-> ", m)
    # m.group(0) is empty because the lookahead consumed 0 characters!
    # m.group(1) contains the 'ana' captured inside the lookahead.
    content = m.group(1)  # The matched content
    index = m.start()  # The starting index of the match
    # span has zero width here, so it gives the position but not the text
    print("span->", m.span()) #
    print(f"Found '{content}' starting at index {index}")
    print('-' * 40) # Separator for clarity

# Output:
# Match object:->  <re.Match object; span=(1, 1), match=''>
# span-> (1, 1)
# Found 'ana' starting at index 1
# Match object:->  <re.Match object; span=(3, 3), match=''>
# span-> (3, 3)


Match object:->  <re.Match object; span=(1, 1), match=''>
span-> (1, 1)
Found 'ana' starting at index 1
----------------------------------------
Match object:->  <re.Match object; span=(3, 3), match=''>
span-> (3, 3)
Found 'ana' starting at index 3
----------------------------------------


[Back to the Table of Contents](#toc)

### <a name="13-26-3-lookbehinds"></a>13.26.3 Lookbehinds

Sometimes you must match something **only if it is preceded by** a pattern, without including that pattern in the result. A lookahead cannot do this, because it checks what comes after; this is the classic case for a lookbehind.

Take the text `"Ms. Alice and Mr. Bob met Dr. Charlie."` with these constraints:

- The titles (Mr., Ms., Dr.) must not appear in the match.
- A name counts only if a title comes before it.

The answer should be `['Alice', 'Bob', 'Charlie']`.

[Back to the Table of Contents](#toc)

### <a name="example-22-a-positive-lookbehind-for-titles"></a>Example 22: A positive lookbehind for titles

**What the code does.** It uses `r"(?<=(?:Mr|Ms|Dr)\.\s)[A-Z][a-z]+"` with `re.findall()` to collect the three names.

**How it works.**

| Part | Meaning |
|---|---|
| `(?<= ... )` | A positive lookbehind: the text just before this position must match |
| `(?:Mr\|Ms\|Dr)` | A **non-capturing** group holding the three titles |
| `\.\s` | A full stop and one space |
| `[A-Z][a-z]+` | The part that is really matched: a capital letter followed by lowercase letters |

**Why the group must be non-capturing.** `findall()` has a special rule: if the pattern contains capturing groups, it returns the **groups** instead of the whole match. With `(Mr|Ms|Dr)` you would get `['Ms', 'Mr', 'Dr']`, which is the opposite of what you want. Writing `(?:Mr|Ms|Dr)` keeps the titles out of the result.

**Learning points**

1. The title is checked but never consumed, so it does not appear in the output.
2. Python's lookbehind must be **fixed width**. `(?:Mr|Ms|Dr)\.\s` is fine, because all three alternatives are two letters long. A pattern such as `(?<=\w+)` would raise an error.
3. The output is `['Alice', 'Bob', 'Charlie']`.

In [28]:
import re

text = "Ms. Alice and Mr. Bob met Dr. Charlie."

# (?<=...) is a POSITIVE LOOKBEHIND
# It asserts that before the current position we have:
#   Mr.  OR  Ms.  OR  Dr.
# Important: The title is CHECKED but NOT INCLUDED in the match
# sp stands for space character. Just a single space here.
# - sp is represented by \s in regex
# - Only the name is captured

pattern = r"(?<=(?:Mr|Ms|Dr)\.\s)[A-Z][a-z]+"
matches = re.findall(pattern, text)
print(matches) # OUTPUT: ['Alice', 'Bob', 'Charlie']



['Alice', 'Bob', 'Charlie']


[Back to the Table of Contents](#toc)

## <a name="scripting-questions-and-assignments"></a>Scripting questions and assignments

The online resource that goes with the book has many script-writing questions, with answers. Every regular expression used in those scripts is explained in comments inside the script.

| | Assignment | What it asks |
|---|---|---|
| 1 | Naming styles | Explain snake_case, camelCase, PascalCase and UPPER_CASE, and write a script that converts camelCase to snake_case and back |
| 2 | Prime numbers | Use the regex in Example 23 below to test whether a number is prime |
| 3 | Password rules | Write a regex for a password with at least one lowercase letter, one uppercase letter, one digit and one special character from `[!@#$%^&*]`, and a length between 6 and 12 |

[Back to the Table of Contents](#toc)

### <a name="example-23-testing-for-a-prime-number-with-a-regular-express"></a>Example 23: Testing for a prime number with a regular expression

**What the code does.** It writes the number n as a string of n ones (`"1" * n`) and then checks whether that string can be split into equal groups. If it can, the number is composite; if it cannot, it is prime.

**How it works.** The pattern is `r'^1?$|^(11+?)\1+$'`, which has two alternatives:

| Alternative | Meaning | Matches |
|---|---|---|
| `^1?$` | An empty string, or a single 1 | n = 0 and n = 1, which are not prime |
| `^(11+?)\1+$` | A group of two or more ones, repeated one or more times, filling the whole string | Composite numbers |

So the regex **matches** exactly when the number is **not** prime. The function returns `True` when `re.match()` gives `None`.

**Learning points**

1. `(11+?)` is lazy, so the engine tries the smallest group first: two ones, then three, and so on. If any size divides the string exactly, the number has a factor.
2. `\1+` is a backreference: the same group of ones must repeat.
3. This is a famous regex trick. It is clever, but it is slow for large numbers; ordinary arithmetic is far better in real code.

In [29]:
import re
def is_prime(n):
    pat_for_prime = r'^1?$|^(11+?)\1+$'
    mo = re.match(pat_for_prime, "1" * n)
    if mo == None:
        return True
    else:
        return False
print('is prime 7->', is_prime(7))  # True
print('is prime 9->', is_prime(9))  # False
print('is prime 11->', is_prime(11))  # True


is prime 7-> True
is prime 9-> False
is prime 11-> True


[Back to the Table of Contents](#toc)

## <a name="beyond-the-book"></a>Beyond the Book

These short extras are not in the book. Skip them on the first reading.

[Back to the Table of Contents](#toc)

### <a name="extracting-structured-data-with-named-groups"></a>Extracting structured data with named groups

Named groups turn a regex into a small parser. This is the everyday use of regular expressions in real programs.

In [30]:
import re

log_lines = [
    "2026-03-14 10:23:01 ERROR disk full",
    "2026-03-14 10:24:17 INFO backup finished",
    "2026-03-15 08:02:55 WARNING low memory",
]

pattern = re.compile(r"(?P<date>\d{4}-\d{2}-\d{2})\s+"
                     r"(?P<time>\d{2}:\d{2}:\d{2})\s+"
                     r"(?P<level>[A-Z]+)\s+"
                     r"(?P<message>.+)")

for line in log_lines:
    m = pattern.match(line)
    if m:
        d = m.groupdict()
        print(f"{d['date']} | {d['level']:<8} | {d['message']}")

2026-03-14 | ERROR    | disk full
2026-03-14 | INFO     | backup finished
2026-03-15 | WARNING  | low memory


[Back to the Table of Contents](#toc)

### <a name="replacing-with-a-function"></a>Replacing with a function

The second argument of `re.sub()` can be a **function** instead of a string. Python calls it once for every match and puts the returned text in place of the match. This lets you compute the replacement.

In [31]:
import re

prices = "Shirt costs 500, trousers cost 1200, shoes cost 2500"

def add_tax(match):
    amount = int(match.group())
    return str(round(amount * 1.18))        # add 18 per cent

print(re.sub(r"\d+", add_tax, prices))

Shirt costs 590, trousers cost 1416, shoes cost 2950


[Back to the Table of Contents](#toc)

### <a name="writing-a-long-pattern-readably-with-re-x"></a>Writing a long pattern readably with re.X

The `re.X` (VERBOSE) flag lets you spread a pattern over several lines and add comments. Whitespace inside the pattern is ignored, so you have to write a space as `\s` or `[ ]`.

In [32]:
import re

phone = re.compile(r"""
    (\+91)?         # an optional country code
    [\s-]?          # an optional space or hyphen
    (\d{10})        # ten digits: the number itself
    """, re.X)

for text in ["+91 9876543210", "9876543210", "12345"]:
    m = phone.fullmatch(text)
    print(f"{text:<16} -> {'valid, number is ' + m.group(2) if m else 'not valid'}")

+91 9876543210   -> valid, number is 9876543210
9876543210       -> valid, number is 9876543210
12345            -> not valid


[Back to the Table of Contents](#toc)

### <a name="a-caution-about-findall-and-groups"></a>A caution about findall() and groups

`findall()` changes its behaviour when the pattern has capturing groups. Knowing the three cases saves a lot of confusion.

In [33]:
import re

text = "tom@example.com, priya@college.edu"

print("No group      :", re.findall(r"\w+@\w+\.\w+", text))       # whole matches
print("One group     :", re.findall(r"(\w+)@\w+\.\w+", text))     # only that group
print("Two groups    :", re.findall(r"(\w+)@(\w+\.\w+)", text))   # tuples
print("Non-capturing :", re.findall(r"(?:\w+)@\w+\.\w+", text))   # whole matches again

No group      : ['tom@example.com', 'priya@college.edu']
One group     : ['tom', 'priya']
Two groups    : [('tom', 'example.com'), ('priya', 'college.edu')]
Non-capturing : ['tom@example.com', 'priya@college.edu']


[Back to the Table of Contents](#toc)