name: Mirror to New Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Push to Mirror
        env:
          TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          git remote add mirror https://x-access-token:${TOKEN}@github.com/ag999git/001-mirror.git
          git push mirror HEAD:main --force
